### ISSUE TITLE
Cache cleaning

### ISSUE THREAD

**Issue by wuputah** [heroku/heroku-buildpack-nodejs#1]
If you remove a package, it is not removed from the cache and those packages are re-installed.

To reproduce: I did a wholesale change of the package.json (was actually a completely different app that I force pushed). The original package.json included mongodb 0.9.6. The second one did not. When I deployed, I saw:

```
-----> Installing dependencies with npm 1.0.8

       > mongodb@0.9.6-7 install /tmp/build_2olrpgftd8j1v/node_modules/mongodb
       > bash ./install.sh

       ================================================================================
       =                                                                              =
       =  To install with C++ bson parser do <npm install mongodb --mongodb:native>   =
       =  the parser only works for node 0.4.X or lower                               =
       =                                                                              =
       ================================================================================
       Not building native library for cygwin
       ejs@0.4.3 ./node_modules/ejs 
       Dependencies installed
```

**Comment by philss** [comment]
Just for the record: I think in the current versions, you need to set `NODE_MODULES_CACHE=false` in order to clean the cache. I'm using version 70 of this buildpack.

**Comment by avinashdv** [comment]
Hi, I have deployed my angular app on heroku and I get the similar error. I was not able to set `NODE_MODULES_CACHE=false` as I have deployed my app via github. Any workaround to set the node_modules_cache to false in this case

**Comment by avinashdv** [comment]
@philss I have deployed my angular app on heroku and I face somthing similar issue and was unable to set `NODE_MODULES_CACHE=false` as I have used github as a medium to deploy. Any other ways that I can set node_modules_cache to false.
