### ISSUE TITLE
Yarn 2 dev dependencies started automatically pruning with no way to skip pruning

### ISSUE THREAD

**Issue by anark** [heroku/heroku-buildpack-nodejs#1007]
**Describe the bug**
As of the last few days deploying an app that uses yarn 2/3 will prune dev dependencies with no way to skip pruning.  I believe this was introduced via https://github.com/heroku/heroku-buildpack-nodejs/pull/1001, however our app relied on having the dev dependencies unpruned.  All docs state that the dependencies are not pruned.  How can we revert to the old behaviour(skip pruning)

**Comment by jimmytang** [comment]
We're running into the same issue! Please help us

**Comment by martinbee** [comment]
#1001 is definitely the cause. We run yarn v2 with workspaces and avoided installing the workspace tools plugin so we could skip pruning, but, looking at `yarn_prune_devdependencies()` now, it looks like yarn v2 will always prune now.

**Comment by anark** [comment]
Yep it does, and setting YARN_PRODUCTION=false does not work with yarn 2/3 so there is now no way I can see to skip pruning which is a major issue for us.  We cant deploy!  And its due to this default changing with no path to use the old behaviour.  Please help

**Comment by xow** [comment]
Hi all, we're experiencing this too. A workaround I've found is to run this command

```sh
heroku buildpacks:set https://github.com/heroku/heroku-buildpack-nodejs#v195 -a my-app
```

Notes:
* you may need to escape the hash with `\#`
* If you hastily added `YARN_PRODUCTION=false` like I did, you'll need to remove it before attempting another deploy, since production isn't a valid yarn config in newer versions
