### ISSUE TITLE
Build error on a yarn v3.2.2 app using pnp

### ISSUE THREAD

**Issue by jfurdell** [heroku/heroku-buildpack-nodejs#1190]
Started seeing a build error on a Yarn pnp project via yarn 3.2.2, building a frontend using create-react-app.  This error started appearing suddenly, same config was previously working as recently as October 2023.  The error doesn't appear locally building the app.

Build log example from:
https://dashboard.heroku.com/apps/monde-sportif-staging/activity/builds/58abc24b-6a62-4895-bb8d-162494a86763

-----> Building on the Heroku-22 stack
-----> Using buildpack: heroku/nodejs
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       USE_YARN_CACHE=true
       NODE_VERBOSE=false
       NODE_ENV=development
       NODE_MODULES_CACHE=false
       
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       engines.yarn (package.json):  unspecified (use default)
       
       Resolving node version 20.x...
       Downloading and installing node 20.10.0...
       Using default npm version: 10.2.3
       Resolving yarn version 1.22.x...
       Downloading and installing yarn (1.22.21)
       Using yarn 3.2.2
       
-----> Restoring cache
       Caching has been disabled because NODE_MODULES_CACHE=false
       
-----> Installing dependencies
       Running 'yarn install' with yarn.lock
       ➤ YN0000: ┌ Resolution step
       ➤ YN0002: │ app-sportif@workspace:. doesn't provide mapbox-gl (p6a22d), requested by @mapbox/mapbox-gl-geocoder
       ➤ YN0002: │ app-sportif@workspace:. doesn't provide mapbox-gl (pafc2d), requested by react-map-gl
       ➤ YN0002: │ app-sportif@workspace:. doesn't provide react (pa3e03), requested by @tanstack/react-query
       ➤ YN0002: │ app-sportif@workspace:. doesn't provide react (pdaea4), requested by @testing-library/react
       ➤ YN0002: │ app-sportif@workspace:. doesn't provide react (pe99d1), requested by @wojtekmaj/react-daterange-picker
       ➤ YN0002: │ app-sportif@workspace:. doesn't provide react (pfd0cc), requested by react-compound-slider
       ➤ YN0002: │ app-sportif@workspace:. doesn't provide react (p2e1f1), requested by react-country-flag
       ➤ YN0002: │ app-sportif@workspace:. doesn't provide react (pfc0e5), requested by react-map-gl
       ➤ YN0002: │ app-sportif@workspace:. doesn't provide react (pbeb43), requested by react-router-dom
       ➤ YN0002: │ app-sportif@workspace:. doesn't provide react (pf172e), requested by use-supercluster
       ➤ YN0002: │ app-sportif@workspace:. doesn't provide react-dom (pe36e5), requested by @testing-library/react
       ➤ YN0002: │ app-sportif@workspace:. doesn't provide react-dom (pf103e), requested by @wojtekmaj/react-daterange-picker
       ➤ YN0002: │ app-sportif@workspace:. doesn't provide react-dom (pf8e74), requested by react-router-dom
       ➤ YN0002: │ app-sportif@workspace:. doesn't provide supercluster (p1233e), requested by use-supercluster
       ➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
       ➤ YN0000: └ Completed
       ➤ YN0000: ┌ Fetch step
       ➤ YN0000: └ Completed in 0s 276ms
       ➤ YN0000: ┌ Link step
       ➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
       ➤ YN0000: └ Completed in 0s 442ms
       ➤ YN0000: Done with warnings in 0s 943ms
       
-----> Build
       Running build (yarn)
       Type Error: Cannot read properties of undefined (reading '/tmp/build_2084f3e2/frontend/.pnp.cjs')
           at rJ (/tmp/build_2084f3e2/.yarn/releases/yarn-3.2.2.cjs:390:12785)
           at NBe (/tmp/build_2084f3e2/.yarn/releases/yarn-3.2.2.cjs:390:13266)
           at Object.Og (/tmp/build_2084f3e2/.yarn/releases/yarn-3.2.2.cjs:390:13506)
           at /tmp/build_2084f3e2/.yarn/releases/yarn-3.2.2.cjs:695:4387
           at Object._a (/tmp/build_2084f3e2/.yarn/releases/yarn-3.2.2.cjs:390:10771)
           at xu.findPackageLocation (/tmp/build_2084f3e2/.yarn/releases/yarn-3.2.2.cjs:695:4342)
           at /tmp/build_2084f3e2/.yarn/releases/yarn-3.2.2.cjs:423:1296
           at Function.from (<anonymous>)
           at sB (/tmp/build_2084f3e2/.yarn/releases/yarn-3.2.2.cjs:423:1040)
           at H9 (/tmp/build_2084f3e2/.yarn/releases/yarn-3.2.2.cjs:423:1621)
-----> Build failed

**Comment by colincasey** [comment]
@jfurdell i'm just getting caught up on this now and noticed your recent builds of `monde-sportif-staging` have been successful. For my own curiosity, was this an application issue, Yarn issue, or something else?

Also, for a build issue like this, consider opening a [support ticket](https://help.heroku.com/) next time. You'll get a much faster response time 😄

**Comment by jfurdell** [comment]
@colincasey It appears to be an issue with Yarn plug-n-play; it would build OK on my machines but fail on the Heroku side.  I disabled pnp in my project and added a 'yarn install' step.  That fixed the issue, although it's not an ideal solution & builds/deployments are much slower now.

**Comment by colincasey** [comment]
Interesting. If you could come up with a minimal reproduction of the error I'd be willing to dig into it further.
