### ISSUE TITLE
add support for pnpm deploys

### ISSUE THREAD

**Issue by renanleonel** [heroku/heroku-buildpack-nodejs#1197]
hi! are there any plans for introducing official support for pnpm deployments on heroku? pnpm is growing popularity owing to reduced disk space usage and performance improvements. and after some research i found only one unofficial [buildpack ](https://elements.heroku.com/buildpacks/unfold/heroku-buildpack-pnpm) for pnpm, which unfortunately did not work for me, and a [closed issue](https://github.com/heroku/heroku-buildpack-nodejs/issues/688) about the same topic without any clarifying answer.

thank you!

**Comment by douglasg14b** [comment]
Why was this marked as completed, was it completed, is there support now?
