### ISSUE TITLE
Update default Node version to 22

### ISSUE THREAD

**Issue by uncleramsay** [heroku/heroku-buildpack-nodejs#1339]
**Is your enhancement request related to a problem? Please describe.**
Node 22 is now Active LTS, but the default version being installed by the buildpack is Node 20.

**Describe the solution you'd like**
Active LTS version gets installed if a version is not specified.

**Describe alternatives you've considered**
We can specify the version, but would prefer to rely on getting the latest.

**Comment by runesoerensen** [comment]
Hi,

Just a quick heads up that the [default version is now version v22.x](https://devcenter.heroku.com/changelog-items/3047).

Thanks!
