### ISSUE TITLE
not rebuilding updated version in package.json

### ISSUE THREAD

**Issue by aaronz8** [heroku/heroku-buildpack-nodejs#159]
Previous push was using node 0.10.32 and email-templates 0.1.8. I tried to push updated code, using node 0.11.14 and email-templates 1.1.2. These version numbers were specified in package.json.

However, when I tried to push the updated code, npm didn't even try to rebuild email-templates. Heroku said -----> Node version changed since last build; rebuilding dependencies but it didn't.

It only started working once I removed email-templates from package.json to force an unbuild, and readded it for the next push to get it to build with the right version.

Is this a legit bug / are there any workarounds for this / is there any way to force rebuild everything?

Referenced from https://github.com/progrium/dokku/issues/752

**Comment by hunterloftis** [comment]
Can you set the buildpack to latest master and then paste the full output of any builds you run?

```
heroku config:set BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-nodejs
git commit -am 'master buildpack' --allow-empty
git push heroku master
```

Thanks!

**Comment by weilu** [comment]
I had a similar issue where npm version wasn't picked up. I set the BUILDPACK_URL then it started working. @hunterloftis time to release the nodejs buildpack?

**Comment by hunterloftis** [comment]
@weilu releasing it Wednesday (I want to wait until all of our support staff, including me, are back from holidays!).

**Comment by weilu** [comment]
sweet :)

**Comment by hunterloftis** [comment]
Released; closing. Please let me know if you run into anything similar.

**Comment by aaronz8** [comment]
Awesome, thanks everyone!
