### ISSUE TITLE
Consider showing warnings / pro tips only on failure

### ISSUE THREAD

**Issue by hunterloftis** [heroku/heroku-buildpack-nodejs#164]
Right now they add a lot of noise that folks ignore. It might be better to only show these when we trap an error... not sure yet.

**Comment by zeke** [comment]
I put the `engines.node` pro-tip in there, but I pretty much never use `engines.node`, so I see my own pro-tip every time I deploy. Nerp.

**Comment by hunterloftis** [comment]
Yeah on the one hand it seems useful, but I ignore them half the time too. However, when builds fail it's nice to at least have some hints about where you might want to look.

**Comment by hunterloftis** [comment]
People ignore `WARNING` as well, so now I'm considering like... ASCII-art dragons or something... ;)
