### ISSUE TITLE
Document using private repos

### ISSUE THREAD

**Issue by hunterloftis** [heroku/heroku-buildpack-nodejs#174]
(in all the forms - private npm repo, private github / bitbucket repo...)

**Comment by aseemk** [comment]
+1

**Comment by abtris** [comment]
+1 

I have problems how setup credentials for npm private registry without add credentials into git repository.

**Comment by kevinohara80** [comment]
@abtris

You'll want to commit an `.npmrc` file to your repo that loads your token from environment variables. Here is the example `.npmrc`

```
@myregistry:registry=http://myregistry.com:8080/
//myregistry.com:8080/:_authToken=${NPM_TOKEN}
```

Then just set your environment variable...

```bash
$ heroku config:set NPM_TOKEN=<your token>
```

**Comment by hunterloftis** [comment]
You folks are awesome. Thanks @kevinohara80!

**Comment by ianwremmel** [comment]
Note that this solution makes local development inconvenient. see https://github.com/heroku/heroku-buildpack-nodejs/issues/363 for more details.

**Comment by peteruithoven** [comment]
The following article with the matching buildpacks seem relevant:
http://zeke.sikelianos.com/npm-and-github-automation-with-heroku/

**Comment by danielleadams** [comment]
Documented here: https://devcenter.heroku.com/articles/preview#private-dependencies
