### ISSUE TITLE
Only install iojs on cedar-14

### ISSUE THREAD

**Issue by hunterloftis** [heroku/heroku-buildpack-nodejs#188]
iojs binary won't run on cedar:

```
remote: -----> Installing binaries
remote:        Downloading and installing node 0.11.15...
remote: /tmp/build_f531618f247eb99bab0551d4ecf64800/.heroku/node/bin/node: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /tmp/build_f531618f247eb99bab0551d4ecf64800/.heroku/node/bin/node)
```

**Comment by TheunisKotze** [comment]
Related: https://github.com/joyent/node/issues/9079

**Comment by misterdjules** [comment]
It may be fixed by https://github.com/joyent/node/commit/59265264d56cfb7ced87f9b3666ec570152c5f47 which will be included in the upcoming 0.11.16 release. If you had some time to test that it would be great!

Thank you!

**Comment by hunterloftis** [comment]
It looks like iojs and node 0.11.15+ are all non-starters on cedar (haven't done conclusive tests, just seen a handful of evidence). Should add tests and warnings in the bp for this.

**Comment by hunterloftis** [comment]
cedar-10 is being sunset.
