### ISSUE TITLE
Memory leak caused by iojs.

### ISSUE THREAD

**Issue by gczene** [heroku/heroku-buildpack-nodejs#189]
Good afternoon guys!

In the last two days we have experienced a serious memory leak issue on heroku, and we had to restart our dynos in every two hours.

After a bit of investigation we found a bug in our `package.json` file.
We had this code:
```JSON
{
    "engines": "0.10.x"
}
```
Instead of this code:
```JSON
{
    "engines": {
        "node": "0.10.x"
    }
}
```

From the deployment log we have found out that heroku started to support iojs, and it seems like iojs became the default engine.

After fixing our package.json file  everything went back to normal.

**Comment by gczene** [comment]
A screenshot of the issue:
![screen shot 2015-01-22 at 10 31 26](https://cloud.githubusercontent.com/assets/3063496/5859834/2e019a58-a255-11e4-9829-c70eb430b959.png)

**Comment by hunterloftis** [comment]
It sounds like the bit of the buildpack parsing engines might have failed (with the unsupported "engines": "version" key) and unintentionally triggered an iojs install. I'll add a test & fix for that, thanks for adding an issue!

**Comment by zeke** [comment]
nice catch!

**Comment by hunterloftis** [comment]
Think this should be fixed; please let me know if you run into it in the future.
