### ISSUE TITLE
hacking info

### ISSUE THREAD

**Issue by kevinburkeshyp** [heroku/heroku-buildpack-nodejs#191]
- which shells are expected/allowed?
- how BSD/GNU compatible does code need to be?
- is writing to the filesystem allowed?

**Comment by tjwebb** [comment]
> how BSD/GNU compatible does code need to be?

node.js code? I don't follow...

> is writing to the filesystem allowed?

Heroku nodes have an ephemeral filesystem that you can write to, but which will be cleaned up whenever a new node is spun up. Use S3 for persistent file storage.

> which shells are expected/allowed?

Again, I don't follow. I don't know what kind of answer you're expecting. If you ssh into your heroku node, you have a bash shell. There's no point in trying to change this, again, because nodes are ephemeral.

**Comment by hunterloftis** [comment]
bash works,
code needs to run on Ubuntu,
filesystem writes are fine (necessary, actually, based on the buildpack API).

Portable is better than unportable.
Simple is better than complex.

**Comment by hunterloftis** [comment]
Also - feel free to open a PR or issue if you're wondering about something specific!

**Comment by kevinburkeshyp** [comment]
Yeah sorry - was thinking about this in particular with BSD vs. GNU versions of `/usr/bin/time`. The BSD time program (which ships by default on Macs) doesn't really support different time formats, which would have required a different approach.

**Comment by kevinburkeshyp** [comment]
All I was asking was to clarify in the docs that bash syntax is OK. There are some lines in the code which suggest it's designed to be run on different types of Unixes - https://github.com/heroku/heroku-buildpack-nodejs/blob/master/lib/common.sh#L61, and I wondered if the same portability requirement applied to shell syntax.

**Comment by hunterloftis** [comment]
Definitely - it's lovely when stuff works locally on osx but certainly not required (already we ship a `jq` binary that's built for Ubuntu). Maybe start quick-and-dirty and we can make stuff more portable if necessary?
