### ISSUE TITLE
Is it possible to precompile assets?

### ISSUE THREAD

**Issue by acroca** [heroku/heroku-buildpack-nodejs#196]
Hi all,

My node app serves some static files that need to be compiled before running the server.
Is there a way to run a task to compile those assets during the build process?

Thanks.

**Comment by longhotsummer** [comment]
+1 it would be useful in the nodejs buildpack exposed some of the event hooks that, say, the python buildpack exposes such as `post_compile'.

**Comment by longhotsummer** [comment]
@acroca I've had success using the `prestart` npm hook when launching the server with `npm start` to kick off a compliation phase, see https://docs.npmjs.com/misc/scripts

**Comment by acroca** [comment]
Interesting, thanks!

**Comment by hunterloftis** [comment]
The buildpack just uses node's built-in hooks (preinstall, postinstall, etc). Most users use the `postinstall` script, eg:

```js
"scripts": {
  "postinstall": "bower install && grunt build && whatever else"
}
```
