### ISSUE TITLE
Possibility to not run `npm install` for prebuilt node_modules

### ISSUE THREAD

**Issue by ehd** [heroku/heroku-buildpack-nodejs#199]
Hey there, I've been wondering whether it would be possible to not run `npm install` if `$modules_source` has been detected as `prebuilt`. Rebuilding native dependencies for the slug's architecture makes sense. But I can't see a reason for running `npm install` for modules already shipped from CI.

[Link to relevant code in build.sh](https://github.com/heroku/heroku-buildpack-nodejs/blob/c8cb21e74f5fac33a4ace8f9ef802434dbf68190/lib/build.sh#L170-174)

Here's the workflow I'm advocating:

1. [local] Push to Github
2. [ci] Install & build node_modules on travis
3. [ci] Run tests
4. [ci] Deploy current working directory to heroku including the very `node_modules` folder that's been used for the successful build
5. [heroku] Run `npm rebuild` to rebuild any native modules for this architecture
6. [heroku] __(Proposed change)__ Don't run `npm install` to eliminate any chance of installing a new dependency version that might be broken

I guess an alternative approach for this is to (also) ship an `npm-shrinkwrap.json` as part of step 4, but I'd rather not run `npm install` on heroku at all if possible.

**Comment by hunterloftis** [comment]
This is something we've looked into (and tried) but it didn't work out as expected:

- https://github.com/heroku/heroku-buildpack-nodejs/issues/104
- https://github.com/heroku/heroku-buildpack-nodejs/issues/47
- https://github.com/heroku/heroku-buildpack-nodejs/issues/17

`rebuild` actually slowed things down, and then we also have to be able to kick off `preinstall` / `postinstall` hooks (essentially simulating `npm install`)... but that's, of course, brittle.

> [heroku] (Proposed change) Don't run npm install to eliminate any chance of installing a new dependency version that might be broken

Npm-shrinkwrap can fix drift between installs. Alternatively, you can `npm install --save-exact` to pin your package.json dependencies.

**Comment by ehd** [comment]
@hunterloftis Got it! Thanks for linking back to the past issues, the conclusions make sense to me.
