### ISSUE TITLE
how are node modules cached?

### ISSUE THREAD

**Issue by jonathanong** [heroku/heroku-buildpack-nodejs#204]
seems like everytime i switch node/iojs versions, i get "could not load the bindings file" for bcrypt. seems like you're not adding the node/iojs version as part of the node modules cache hash

**Comment by hunterloftis** [comment]
strange, it should invalidate your cache whenever you change node versions:

- https://github.com/heroku/heroku-buildpack-nodejs/blob/master/lib/build.sh#L239
- https://github.com/heroku/heroku-buildpack-nodejs/blob/master/lib/build.sh#L262

Any chance you'd be interested in writing a test, or even just giving me very specific reproduction instructions?

**Comment by aseemk** [comment]
Psst... press `y` on those links to set them to the current commit. Otherwise, those line numbers may become stale as the file changes on `master`.

**Comment by hunterloftis** [comment]
@aseemk thanks, I've seen that tip before but always forget ;)

**Comment by hunterloftis** [comment]
Closing for now as I can't repro; if you continue to run into this even after https://github.com/heroku/heroku-buildpack-nodejs/pull/236 please reopen!
