### ISSUE TITLE
make it possible to run unit tests within build container

### ISSUE THREAD

**Issue by tomyan** [heroku/heroku-buildpack-nodejs#205]
Is it possible to cause the tests (i.e. "npm test") during the build? We would like to be able to do this so that we can avoid installing dependencies on our CI environment, as well as ensuring we run the tests with the same runtime, dependences, etc. Happy to add a pull request if this seems like a good idea. Otherwise, any suggestions about best practices for running unit tests within our build pipeline would be appreciated.

Thanks

Tom

**Comment by aseemk** [comment]
I'm interested & intrigued by this idea.

One easy way to achieve this now @tomyan is to just add `npm test` as a `postinstall` hook.

**Comment by hunterloftis** [comment]
@tomyan @aseemk yep the simple way is to run them as a hook.

Keep in mind we enforce a build timeout - I think 15 minutes - so if they're slow-running tests you may end up hitting that.

**Comment by tomyan** [comment]
@aseemk: that seems to work well. We run them conditionally based on the presence of an environment variable (having the tests run whenever a developer runs `npm install` would be surprising to people coming the project).

@hunterloftis: thanks for the heads-up. I would hope our unit tests would never hit this.

Kinda wish all buildpacks would provide the ability to do this (my team maintains jenkins for a number of teams working with different buildpacks).

**Comment by hunterloftis** [comment]
closing as resolved.

Also @tomyan we're investigating better ways to hook into workflows (github -> CI -> heroku), so expect more updates there soon!
