### ISSUE TITLE
Allow enabling dev dependencies via npmrc

### ISSUE THREAD

**Issue by aseemk** [heroku/heroku-buildpack-nodejs#206]
Not sure if this issue could/should be generalized more, but see conversation here: https://github.com/heroku/heroku-buildpack-nodejs/pull/203#issuecomment-85168530

We check our `node_modules` into git, and those include dev dependencies. The buildpack now prunes them, but that's unnecessary for us since they're already there. (They're convenient to test things manually via `heroku run bash`, etc.)

We can set a config var, `NPM_CONFIG_PRODUCTION=false`, but it'd feel better to be able to specify this in code instead, since (a) it's then alongside our checked-in `node_modules`, and (b) it doesn't need to vary across our different deployments of this app (e.g. production, staging, development).

I've tried this via an `.npmrc` file, but it doesn't take precedence over the environment variable, and the buildpack explicitly sets this environment variable.

Edit: useful reference:

https://docs.npmjs.com/misc/config
https://docs.npmjs.com/misc/config#production

**Comment by hunterloftis** [comment]
I like this idea, but given the need for config via env vars, backwards compatibility, and the precedence rules of npm, I haven't come up with a great way to make this feature happen.

Closing for now; I'd be open to a PR that solves the issue without breaking current user apps though.

**Comment by nmccready** [comment]
This is a semi serious issue with more relevance to this bug.
https://github.com/npm/npm/issues/11766

**Comment by hunterloftis** [comment]
@nmccready did you try `heroku config:set NPM_CONFIG_PRODUCTION=false` ?

The alternative is to just move the package from devDependencies to dependencies.

**Comment by nmccready** [comment]
Yeah we realize the fix and we just moved the dependency to deps; but I just wanted to make people aware of where you might run into this problem.
