### ISSUE TITLE
Build shouldn't fail if a specified cache-able directory isn't found

### ISSUE THREAD

**Issue by hunterloftis** [heroku/heroku-buildpack-nodejs#207]
Eg:

```
Storing directories:
- frontend/node_modules
cp: cannot stat ‘/tmp/build_03756bc1c76eca450163f1994599c295/frontend/node_modules’: No such file or directory
```

Probably just need to add a test here:

- https://github.com/heroku/heroku-buildpack-nodejs/blob/40214da800dadf60b9a746514ea55140f5863380/lib/build.sh#L275

**Comment by sirvine** [comment]
I ran into this problem today as well.

**Comment by hunterloftis** [comment]
Fixed by https://github.com/heroku/heroku-buildpack-nodejs/pull/236
