### ISSUE TITLE
Recommended way of customizing build process?

### ISSUE THREAD

**Issue by jbuck** [heroku/heroku-buildpack-nodejs#214]
Hi there!

When we build our app, we try to make local development as easy as `npm install && npm start`. When we're running our code on Heroku we'd like to run an optimized build for smaller file sizes. We're currently using a separate node script (Windows compatibility) to do something like this in the postinstall:

##### package.json
```
  "postinstall": "node scripts/postinstall.js",
```

##### scripts/postinstall.js
```
// You could use any environment variable, but this one is defined by Heroku nodejs buildpack already, so lets use it
if (process.env.NPM_CONFIG_PRODUCTION === "true") {
  // Run optimized build
} else {
  // Run unoptimized build
}
```

Can you suggest any optimizations here? Thanks!

**Comment by hunterloftis** [comment]
Looks like you're already doing it well @jbuck - and kudos for keeping local dev so easy. It's a best practice that not many follow!
