### ISSUE TITLE
Copy `.scripts.start` instead of setting `npm start` in default Procfile

### ISSUE THREAD

**Issue by stuartpb** [heroku/heroku-buildpack-nodejs#217]
Since `npm start` doesn't `exec` to replace itself with its child process (npm/npm#4603) the way `bash -c` does, `npm start` ends up eating important signals, and servers don't receive them (meaning that, on a Docker-based system like Plusku or Dokku, the `docker stop` call ends up taking 10 seconds and then hard-killing the app).

Unless/until npm/npm#4603 is fixed, build.sh should *copy* the start command defined in package.json *directly* into the default Procfile, rather than inserting "npm start" in the Procfile.

**Comment by hunterloftis** [comment]
Yeah docker + npm can be rough.

However, copying the contents of 'npm start' isn't a viable solution, since npm does other things besides just executing the commands. For example, it also appends `node_modules/.bin` to the subshell `$PATH` so that npm installed binaries can execute.... and it probably does other things I'm not aware of as well (and don't want to track / duplicate).

We want to be explicit, direct, and DRY, so trying to duplicate npm's existing start mechanism is out of scope for the buildpack. If a user wants some explicit behavior from their `Procfile`, all they have to do is provide a `Procfile` with whatever start mechanism they prefer.

**Comment by stuartpb** [comment]
> Yeah docker + npm can be rough.

This isn't a Docker issue. This is an issue on *any system* where an app that doesn't respond to SIGTERM will be forcibly killed after a period of time: I know Docker does it after 10 seconds, and I'm betting Heroku works a similar way.

Killing apps rather than waiting for them to finish what they're doing is a problem, one where you're liable to get half-responses to large requests and half-writes to datastores, which can cause model corruption and/or important transactions to be lost entirely.

> npm does other things besides just executing the commands. For example, it also appends node_modules/.bin to the subshell $PATH so that npm installed binaries can execute....

[Something this buildpack already does anyway.](https://github.com/heroku/heroku-buildpack-nodejs/blob/master/lib/build.sh#L205).

> and it probably does other things I'm not aware of as well (and don't want to track / duplicate).

[No, not really.](https://github.com/npm/npm/blob/master/lib/utils/lifecycle.js) (To be pedantic, there's an unrelated nit for supporting install scripts (putting the node-gyp binary in the PATH) - something no server would use or even know about.)

> We want to be explicit, direct, and DRY, so trying to duplicate npm's existing start mechanism is out of scope for the buildpack. If a user wants some explicit behavior from their Procfile, all they have to do is provide a Procfile with whatever start mechanism they prefer.

Yeah, and app authors want to be DRY, too - that means *not* duplicating the start mechanism they already specify in package.json in the codebase. Specifying fields within package.json is not the same as saying "I want to go through npm" - package.json is a minimal definition of fields to be used by *any* tools or platforms (such as how Nodejitsu used it).

**Comment by hunterloftis** [comment]
If you don't want to go through npm, there is already a simple solution: provide whatever command string you like in a Procfile.

`npm start` is just a default, and a very easy one to override at that.
