### ISSUE TITLE
Handle applications outside root path

### ISSUE THREAD

**Issue by Irio** [heroku/heroku-buildpack-nodejs#221]
## Problem

My repository is composed by two distinct applications: a Rails app, located in the root path, and a Node.js one responsible for handling assets, located in `app/assets`.

```
app/assets
├── images
├── javascripts
├── node_modules
├── stylesheets
└── package.json
```

Following this configuration, my Node.js is not detected by the buildpack. The reason I have to keep it inside `app/assets` is because it's just a sidekick app, so should follow Ruby on Rails conventions.

## Proposal

Provide a way to tell the buildpack that the application is outside the root path and thus, do all the steps - detection, compilation and release - inside the given namespace. This could happen using an environment variable called `NODEJS_BUILDPACK_PATH` or similar and `cd`'ing to the folder before running each script.

**Comment by hunterloftis** [comment]
Thanks for the concise documentation and proposal!

Is the node app actually an executing app? ie, it has a process declared in your `Procfile`?

**Comment by Irio** [comment]
Thank you for the quick feedback. :racehorse: 

Today, no. Node is there just for handling JS dependencies, which it's super easy to do in it while has been difficult in the Rails app.

```sh
### Node.js buildpack

# Automatically run by buildpack.
$ npm install
# Might be off topic (tough a bit relevant for explaining the why's),
# but is responsible for packing libraries to be read by Sprockets in the Rails app.
# The command is located in my package.json's postinstall.
$ webpack

### Rails buildpack

# Does its job expecting to have libraries and anything else bundled by webpack
# (compiled *.jsx files, in my case) already available in app/assets.
```

*(Yet, I can think in use cases for keeping both Node and Rails running processes at the same time)*

**Comment by hunterloftis** [comment]
Let me see if I can help you with this particular issue, and I'll leave the topic open for discussion. I'd like to avoid non-root builds to keep maintenance complexity down. Root builds also encourage good 12factor architecture (http://12factor.net/codebase). However, maybe there's an overriding reason for them.

For now, try adding this to a top-level package.json:

```json
{
  "scripts": {
    "postinstall": "cd assets && npm install"
  }
}
```

**Comment by Irio** [comment]
Perfect, @hunterloftis. I can totally understand your point and your suggestion already accomplishes what I wanted.

**Comment by hunterloftis** [comment]
Great!

**Comment by pushred** [comment]
Could this approach cause any issues with the current working directory of a later buildpack? For some reason I have a Rails app that is failing to start after successfully getting through the node buildpack and all the Bundler deps and rake tasks. Very oddly the Puma server defined in our Procfile seems to be attempting to load a node module residing in `/app/assets/src/index.js` or `/app/assets/javascripts/application.js`.

I provided more details in a [support ticket](https://help.heroku.com/tickets/272440) but really having a hard time understanding why this is happening if the Procfile isn't defining that path or anything node-related.

**Comment by hunterloftis** [comment]
That issue appears to be from requiring 'jQuery' instead of 'jquery' (on Linux, file cases must match).

**Comment by tomasdev** [comment]
:(

would have loved to have a configurable path via Procfile

**Comment by angadsalaria** [comment]
+1 for above comment.
