### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by focusaurus** [heroku/heroku-buildpack-nodejs#226]
I don't see any existing issues about supporting OSX, so I'll file this to discuss. I see at least 2 issues so far:

1. vendored linux jq binary
  - Could we use a bash JSON parser such as [this one based on JSON.sh]
(https://gist.github.com/assaf/ee377a186371e2e269a7) instead of jq?
  - https://github.com/dominictarr/JSON.sh
2. `mktemp` is different on OSX and it's use in `bin/compile` so far seems unnecessary

My thought is if OSX support is within reasonable reach, I'd like to see this tool get more use for local developer builds on their OSX systems. If it turns out to be quite difficult to support, I'll understand if this is closed as out of scope/interest.

**Comment by hunterloftis** [comment]
Thanks for the PR!
