### ISSUE TITLE
package.json node_modules_cache environment variable should overwrite cacheDirectories

### ISSUE THREAD

**Issue by jonathanong** [heroku/heroku-buildpack-nodejs#233]
the env var, if defined by me, the user, should overwrite the existence of `node_modules` in `cacheDirectories`. this should make it easier for us to prune the cache. 

- `cacheDirectories` does not include `node_modules` and `NODE_MODULES_CACHE` is not defined -> cache
- `cacheDirectories` includes `node_modules` and `NODE_MODULES_CACHE` is not defined -> cache
- `cacheDirectories` includes `node_modules` and `NODE_MODULES_CACHE` is `true` -> cache
- `cacheDirectories` includes `node_modules` and `NODE_MODULES_CACHE` is `false` -> don't cache
- `cacheDirectories` does not include `node_modules` and `NODE_MODULES_CACHE` is not defined -> cache
- `cacheDirectories` does not include `node_modules` and `NODE_MODULES_CACHE` is `true` -> cache
- `cacheDirectories` does not include `node_modules` and `NODE_MODULES_CACHE` is `false -> no cache

in particular, i need this to fix https://github.com/npm/npm/issues/8052 while still being able to cache `node_modules`.

maybe another question: should i just not ever define `node_modules` in `cacheDirectories`? you guys recommend that we do: https://devcenter.heroku.com/articles/nodejs-support#cache-behavior

**Comment by hunterloftis** [comment]
Hi @jonathanong, just merged simplified caching behavior into master:

- https://github.com/heroku/heroku-buildpack-nodejs/blob/2e2f28b735713fd6f6d369e3c07aa1dfa0788f73/bin/compile#L90-L107

Basically if `NODE_MODULES_CACHE` is `false` -> skip cache
If a runtime version (node, npm) has changed -> skip cache
If `cacheDirectories` exists -> restore whatever dirs are listed in `cacheDirectories`
If `cacheDirectories` doesn't exist -> restore `node_modules`
