### ISSUE TITLE
Syntax error in build.sh

### ISSUE THREAD

**Issue by PeterDaveHello** [heroku/heroku-buildpack-nodejs#234]
Got this error when deploying
> remote: /tmp/buildpackPy5c7/lib/build.sh: line 258: TRUE: command not found

**Comment by hunterloftis** [comment]
@PeterDaveHello can you provide more context? I'd be very surprised if there's a syntax error (tests are passing and only about 1% of builds are failing).

**Comment by PeterDaveHello** [comment]
Okay I will.

**Comment by PeterDaveHello** [comment]
I got this msg when deploying, thanks!
> remote:        cache directory...
> remote:        environment variables...
> remote: 
> remote:        Node engine:         0.10.x
> remote:        Npm engine:          unspecified
> remote:        Start mechanism:     Procfile
> remote:        node_modules source: package.json
> remote:        node_modules cached: true
> remote: 
> remote:        NPM_CONFIG_PRODUCTION=true
> remote:        NODE_MODULES_CACHE=TRUE
> remote: 
> remote: -----> Installing binaries
> remote:        Resolving node version 0.10.x via semver.io...
> remote:        Downloading and installing node 0.10.38...
> remote:        Using default npm version: 1.4.28
> remote: 
> remote: -----> Building dependencies
> remote: **/tmp/buildpack1tgMf/lib/build.sh: line 258: TRUE: command not found**
> remote:        Installing node modules
> remote:

**Comment by hunterloftis** [comment]
Could you open a support ticket (help.heroku.com) so I can take a look at your application's code and config?

**Comment by PeterDaveHello** [comment]
This is the repo, it's opensourced, don't know if this is enough? Thank you very much!
https://github.com/cdnjs/new-website

By the way, the deployment still working, just think that there should not be a syntax error.

**Comment by hunterloftis** [comment]
I'm actually more interested in the env vars than in the source code. Since that line is just an if statement (that doesn't appear to create errors in the test suite or in other app deploys) I'm trying to figure out what's unique about this app in order to debug why that error might appear.

**Comment by hunterloftis** [comment]
(but I'll clone & deploy that site to see if it is the code itself)

**Comment by hunterloftis** [comment]
@PeterDaveHello aha, I think that's it - on an arbitrary project if I `heroku config:set NODE_MODULES_CACHE=TRUE` I get the same syntax error. Thank you for pointing this out!

(also, for now you can run `heroku config:unset NODE_MODULES_CACHE` in order to avoid the error in your own project. It's true by default)

**Comment by PeterDaveHello** [comment]
hmmmm ... sorry about that, but actually I use git directly xD

**Comment by PeterDaveHello** [comment]
So do I still need to open an issue ticket?

**Comment by hunterloftis** [comment]
Nope no worries, thanks for your help. I can reproduce it now.

**Comment by PeterDaveHello** [comment]
:+1:

**Comment by hunterloftis** [comment]
It looks like this is just because, unlike osx, ubuntu + bash doesn't recognize `TRUE/FALSE` as booleans (instead, use `true/false`). You can see this for yourself:

```
~ $ if TRUE; then echo 'true'; fi
bash: TRUE: command not found
~ $ if true; then echo 'true'; fi
true
~ $ exit
exit
(v0.10.38, 1.4.28):~/test/express (master)$ if TRUE; then echo 'true'; fi
true
```

**Comment by PeterDaveHello** [comment]
Can we try to prevent this on ubuntu + bash?
This msg on the build process looks not so reasonable.
