### ISSUE TITLE
Caching non-root node_modules folder?

### ISSUE THREAD

**Issue by thejspr** [heroku/heroku-buildpack-nodejs#241]
We have our frontend code within a `client/` folder, with npm modules installed in `client/node_modules`. Is there any way to cache this folder so we don't have to reinstall all npm modules on each deploy?

**Comment by grantgeorge** [comment]
Try adding this line to your packagee.json file:

    "cacheDirectories": ["./client/node_modules", "./client/bower_components"]

Ref:

https://devcenter.heroku.com/articles/nodejs-support#cache-behavior

**Comment by hunterloftis** [comment]
Thanks @grantgeorge, that's exactly right.

**Comment by thejspr** [comment]
Thanks @grantgeorge
