### ISSUE TITLE
Wrong link in `node_modules/.bin` when using a cache directory

### ISSUE THREAD

**Issue by robinmonjo** [heroku/heroku-buildpack-nodejs#242]
Hello,

I use this buildpack in an app used to build some apps and then send the build onto amazon S3. Since recently, when I build an app without any cache directory, I end up with this in the `node_modules/.bin` directory:

````bash
cake -> ../coffee-script/bin/cake
coffee -> ../coffee-script/bin/coffee
express -> ../express/bin/express
js-yaml -> ../js-yaml/bin/js-yaml.js
````

This is good, the link are ok. However if I build the app again with the cache directory generated by the previous build, I end up with this:

````bash
cake -> <root_path_to_the_cache_directory>/cache/coffee-script/bin/cake
coffee -> <root_path_to_the_cache_directory>/cache/coffee-script/bin/coffee
express -> <root_path_to_the_cache_directory>/cache/express/bin/express
js-yaml -> <root_path_to_the_cache_directory>/cache/js-yaml/bin/js-yaml.js
````

Looks like that when a cache directory exists, the links are fully resolved which make the build impossible to run from outside the machine that actually made the build.

Let me know if this is not clear enough.

Regards,

**Comment by hunterloftis** [comment]
Thanks for the detailed report! Could you provide steps to reproduce the issue exactly? I'd like to add a test for it to the buildpack along with a fix.

**Comment by robinmonjo** [comment]
Hum thanks for asking me this, I tried to reproduce but couldn't. It seems like the issue come from the fact that I tar the cache directory before re-using it and symlinks in `node_modules/.bin` seems to break during this process.
Thx
