### ISSUE TITLE
Update for 14 GB Performance dynos?

### ISSUE THREAD

**Issue by aseemk** [heroku/heroku-buildpack-nodejs#256]
Hey there,

We were excited to hear that Performance dynos now offer 14 GB of RAM, up from 6 GB.

Based on that, we've been waiting for a higher `WEB_CONCURRENCY` to kick in, but it hasn't yet.

I debugged a bit, and am guessing the culprit is that 6 GB is hardcoded in the buildpack here:

https://github.com/heroku/heroku-buildpack-nodejs/blob/e14c33b6f56691016e76ef57278c4147070d6fe6/profile/nodejs.sh#L25

Does this need to be updated? Thanks.

**Comment by aseemk** [comment]
Working around for now by manually doing `heroku config:set MEMORY_AVAILABLE=14336`.

**Comment by aseemk** [comment]
And how 2.5 GB for Performance-M dynos.

https://devcenter.heroku.com/changelog-items/696

**Comment by hunterloftis** [comment]
That update is already in: https://github.com/heroku/heroku-buildpack-nodejs/blob/master/profile/nodejs.sh#L25

Waiting on Performance-L to test / make sure that recommending 28x (!!) is reasonable.

**Comment by aseemk** [comment]
Nice, thanks!

And yep, haha, love the massive concurrency boost.

**Comment by hunterloftis** [comment]
If you'd like to try out Performance-L:

```
heroku buildpacks:set https://github.com/heroku/heroku-buildpack-nodejs#performance-l
```

**Comment by hunterloftis** [comment]
This is all merged in with the standard buildpack now.
