### ISSUE TITLE
Compatibility with python buildpack

### ISSUE THREAD

**Issue by stefanosala** [heroku/heroku-buildpack-nodejs#261]
Hi folks,
we were on our way to try the new node v4.0.0, but it seems it can't get installed.

We updated package.json adding:
  "engines": {
    "node": "^4.0.0",
    "npm": "^2.0.0"
  },

But if we run a bash process, it seems we're still using node v0.10:
~ $ node -v
v0.10.40

Please note that we are using these buildpacks:
=== receiptful-staging Buildpack URLs
1. https://github.com/heroku/heroku-buildpack-nodejs
2. https://github.com/heroku/heroku-buildpack-python

Our guess is that the python buildpack is overriding the node binary. In fact if we remove the python buildpack we get the node v4 binary.

Does anyone ever encountered the same issue?

**Comment by hunterloftis** [comment]
I think you may be running into the same issue as these folks:

- https://github.com/heroku/heroku-buildpack-nodejs/issues/230#issuecomment-102648352

The python buildpack relocates from the build directory and into /app, which appears to override some things. /cc @kennethreitz

**Comment by stefanosala** [comment]
Thanks @hunterloftis 
I found a workaround for this: basically I switched the order of the buildpacks and I forked the node one adding a `rm -rf "$BUILD_DIR/.heroku/node/"` before installing node. (See https://github.com/Receiptful/heroku-buildpack-nodejs/commit/6950be1681dff5b521551f7cbede24de4916c23b)

Although this is not ideal it does the trick for the moment.
