### ISSUE TITLE
Update to latest stable Node.js v4.0.0

### ISSUE THREAD

**Issue by nordisk** [heroku/heroku-buildpack-nodejs#262]
Hi. 

The latest stable version linked from this repo is `v0.12.7`. Can we upgrade to the latest stable version: https://nodejs.org/en/

/cc @nicklester

**Comment by stefanosala** [comment]
I can install the latest version of node with this buildpack, all you have to do is update your engine section of your `package.json` file. See https://devcenter.heroku.com/changelog-items/716?utm_source=dlvr.it&utm_medium=twitter

**Comment by nordisk** [comment]
Cheers. I wasn't sure because of this link here on the `heroku-buildpack-nodejs` main page `Default: the latest stable version.`
