### ISSUE TITLE
Adding N|Solid support

### ISSUE THREAD

**Issue by wblankenship** [heroku/heroku-buildpack-nodejs#264]
I've opened a PR (https://github.com/heroku/heroku-buildpack-nodejs/pull/263) with a first pass at getting N|Solid onto Heroku for one of my apps.

Note: Heroku only supports a single port from what I can tell, so the cli/proxy/etc won't work. This configuration only allows for the policy files to lock down the behaviour of the Node app.

https://github.com/heroku/heroku-buildpack-python/issues/223 will almost certainly affect this.

**Comment by hunterloftis** [comment]
How does the runtime profiling system for N|Solid work? Is it essentially a remote connection ala remote inspector? If so, it might be worth investigating some tunneling options for exposing more ports.

**Comment by wblankenship** [comment]
refer to #263
