### ISSUE TITLE
Any chance to support --with-full-icu build flag?

### ISSUE THREAD

**Issue by stefanosala** [heroku/heroku-buildpack-nodejs#283]
I see the nodes binaries are downloaded from a Heroku url, so I'm not sure it's possible, but it would be really nice to have.

Thanks :)

**Comment by hunterloftis** [comment]
The bins are pulled down from an s3 mirror of nodejs.org/dist - so they're just the standard distributions with small ICU.

You might try this for a works-today solution: https://github.com/icu-project/full-icu-npm

Alternatively, it could make sense to provide something like a `NODE_BIN_URL` value that defaults to our vanilla versions but could point wherever you like.

**Comment by stefanosala** [comment]
Thanks Hunter, we'll use that package for the moment.

Supporting `NODE_BIN_URL` could be a good "easy" alternative and I'll have a look to implement it if we notice the package is not performant enough.

Thanks again for your support, I'm going to close this issue for the moment.
