### ISSUE TITLE
App environment variables not expanded, no way to whitelist

### ISSUE THREAD

**Issue by jonnor** [heroku/heroku-buildpack-nodejs#284]
We set up private NPM as suggested in #174, with `NPM_TOKEN envvar. However during build, the token was not replaced`*`. We never saw any printout mentioning the setting of these envvars from the app config. Looking into the buildpack, it seems that the envvar logic [requires whitelisting](https://github.com/heroku/heroku-buildpack-nodejs/blob/master/lib/environment.sh#L27) of vars to expose (makes sense). However there is no way to whitelist such vars, the argument is [not even passed](https://github.com/heroku/heroku-buildpack-nodejs/blob/master/bin/compile#L64).

This means we could not use the proposed method in issue 174.

`*:` also for some reason NPM did not consider this a failure, causing an entirely borked deploy...

**Comment by hunterloftis** [comment]
The whitelist is an optional argument; in the node buildpack it's left empty, so you can provide any env vars you like:

https://github.com/heroku/heroku-buildpack-nodejs/blob/67291e8c9afa15720219652e490d34d9d28735a6/bin/compile#L64

This is tested here:

https://github.com/heroku/heroku-buildpack-nodejs/blob/67291e8c9afa15720219652e490d34d9d28735a6/test/run#L388-L397

Can you provide a self-contained reproduction of the issue?
