### ISSUE TITLE
Fail on 'UNMET DEPENDENCY' string

### ISSUE THREAD

**Issue by hunterloftis** [heroku/heroku-buildpack-nodejs#288]
Npm has many [open issues about unmet dependencies](https://github.com/npm/npm/search?q=unmet+dependency&type=Issues&utf8=%E2%9C%93). However, unmet dependencies [don't trigger an exit code](https://github.com/npm/npm/issues/7494) to fail the build, which can lead to Heroku users deploying code that will fail at run-time instead of build time, despite the clear build error.

For now, a workaround may be in order - we already record the build stream, so we could grep for `UNMET DEPENDENCY` and fail the build ourselves if we see it.

**Comment by rochapablo** [comment]
Hey, I'm still getting this error:

```
remote: -----> Build succeeded!
remote:        ├── UNMET PEER DEPENDENCY angular@1.6.1
remote:        ├── UNMET PEER DEPENDENCY angular-animate@1.6.1
remote:        ├── UNMET PEER DEPENDENCY angular-aria@1.6.1
remote:        ├── angular-material@1.1.1
remote:        ├── angular-messages@1.6.1
remote:        ├── angular-resource@1.6.1
remote:        ├── angular-ui-router@0.3.2
remote:        ├── angular-ui-router.statehelper@1.3.1
remote:        ├── compression@1.6.2
remote:        ├── concurrently@3.1.0
remote:        ├── express@4.14.0
remote:        ├── gulp@3.9.1
remote:        ├── gulp-concat@2.6.1
remote:        ├── gulp-sass@3.1.0
remote:        └── jquery@3.1.1
remote:
remote:  !     Unmet dependencies don't fail npm install but may cause runtime issues
remote:        https://github.com/npm/npm/issues/7494
```

**Comment by rochapablo** [comment]
Hey,

I did not solve the problem but I put a tape on it. In deed **UNMET PEER DEPENDENCY** is a dependence of a dependence so the way that I see, if this isn't fixed by the root dependence there's no much to be done.

That said here's what I did; ``` "angular-ui-router.statehelper": "^1.3.1", ``` was the villain, his dependence is asking for a low version, so I report the issue as many others did and I download the version *(1.3.1)* myself for non-versioned use.

As I said, this was a workaround and I did this because I was in a hurry.

**Comment by TangeniThePyGuru** [comment]
"Unmet dependencies don't fail npm install but may cause runtime issues"

i get the above error when deploying angular app on heroku

**Comment by jmorrell** [comment]
@TangeniThePyGuru do you experience any issues stemming from this message?

**Comment by ctrlaltdylan** [comment]
Seems like this is just common sense good practice to fail a build if the dependencies aren't met.

Is there a customization of the Heroku deploy command where we can enable this option?
