### ISSUE TITLE
Buildpack writes to itself

### ISSUE THREAD

**Issue by jaraco** [heroku/heroku-buildpack-nodejs#289]
In [VR 178](https://bitbucket.org/yougov/velociraptor/issues/178/vr-buildpacks-not-writable-during), I encountered an issue where builds will fail with this buildpack because the buildpack is attempting to write a file to itself.

I just read through the [buildpack API](https://devcenter.heroku.com/articles/buildpack-api) and it seems to be underspecified if a buildpack should be allowed to write to the buildpack directory. It seems like bad practice to me as it could create conflicts with the commits to the repository.

Question - should the `export` file be written to the $BUILD_DIR or $CACHE_DIR? Or should buildpack builders ensure that the buildpack is writable by the builder process owner?

**Comment by hunterloftis** [comment]
Part of the multi-buildpack API is [exporting an environment for subsequent buildpacks](https://github.com/heroku/heroku-buildpack-multi/blob/26fa21ac7156e63d3d36df1627329aa57f8f137c/bin/compile#L54-L57).

It didn't appear to be documented anywhere, including the buildpack API, so I just [added it](https://devcenter.heroku.com/articles/buildpack-api#providing-an-environment-for-subsequent-buildpacks).

**Comment by jaraco** [comment]
Very useful. Thank you.
