### ISSUE TITLE
Weird characters when git pushing from CI server

### ISSUE THREAD

**Issue by robgraeber** [heroku/heroku-buildpack-nodejs#292]
Hey I've been noticing some weird characters when git pushing from jenkins or other CI services. Works fine locally, something to do with encoding?

```
[1G[1G-----> Installing binaries[K
[1G[1G       engines.node (package.json):  4.2.x[K
[1G[1G       engines.npm (package.json):   unspecified (use default)[K
[1G[1G       [K
[1G[1G       Resolving node version 4.2.x via semver.io...[K
[1G[1G       Downloading and installing node 4.2.6...[K
```

**Comment by fiznool** [comment]
The weird characters are actually [ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code). These tell a regular terminal to do specific things, like add colour to text, or move the cursor to the beginning of the line.

In the case of Jenkins, the console output is converted into HTML. There are two options to stop the weirdness:

1. Use the [ANSIColor Plugin](https://wiki.jenkins-ci.org/display/JENKINS/AnsiColor+Plugin)
2. Strip the ANSI codes from the console output, using `sed`:

``` sh
build_command | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g"
```

**Comment by robgraeber** [comment]
@fiznool awesome you're the man
