### ISSUE TITLE
Try hashing package.json to skip npm install

### ISSUE THREAD

**Issue by hunterloftis** [heroku/heroku-buildpack-nodejs#299]
For large dependency trees, `npm i` can take a while. Sometimes upwards of 10s for what's essentially a no-op.

I suspect that npm client alternatives like ied might solve this problem altogether, but in the meantime it would be interesting to test hashing package.json and skipping the installs with empty diffs.

Need to remember to trigger `preinstall` and `postinstall` scripts.

/cc @hone @tomdale

**Comment by tomdale** [comment]
As @hone mentioned to me, if we adopt this strategy we probably need to mindful of shrinkwrap files as well.

**Comment by hunterloftis** [comment]
yarn is super fast with existing builds; closing this now that we have yarn support.
