### ISSUE TITLE
Memory doesn't get released / garbage collected?

### ISSUE THREAD

**Issue by PanMan** [heroku/heroku-buildpack-nodejs#301]
I amost can't believe this has something to do with the buildpack, but it also doesn't seem to have anything to do with my code, so it does seem heroku specific: Anything I run under NodeJS on Heroku doesn't seem to get its memory garbage collected.
The code below, when run in Node, on my laptop (OSX) takes some 20 MB of memory, but also releases it. On heroku it takes 20 MB, and never releases. I tried this on a brand new app, with only the Node buildpack set up.
Basically, I don't think there is anything wrong with this code, (which is obviously just a test case), so I think there is something wrong somewhere on heroku. 

````
var testString="0123456789";

setInterval(function (){
  console.log("Mem:", Math.round(process.memoryUsage().rss/1000000), " Mb ", process.memoryUsage(), "Len:",testString.length);
}, 1 * 1000);
  
for (i=0;i<20;i++){
  testString=testString+testString; //Double: 10 * 10 ^ 
}
//Now testString=10.000.000 characters, which is roughly 20 Mb.

setTimeout(function(){
  testString="";
  //Now back to 0;
},2000)
````

**Comment by hunterloftis** [comment]
The buildpack just installs dependencies etc (like node). It doesn't change anything about the way node executes. On Heroku, node is just the vanilla binary from nodejs.org running on Ubuntu.

It's completely normal for node to not garbage collect immediately. Node uses a lazy and greedy garbage collector, trying to avoid slowing your app with GC as much as possible. You can fiddle with v8's gc knobs to change this behavior somewhat:

- https://blog.heroku.com/archives/2015/11/10/node-habits-2016#7-avoid-garbage
