### ISSUE TITLE
"npm start" wastes a lot of RAM

### ISSUE THREAD

**Issue by tjwebb** [heroku/heroku-buildpack-nodejs#302]
https://github.com/heroku/heroku-buildpack-nodejs/blob/b5d7dfc63b2e4c6f9d5f75189dc33e34d6027f71/bin/release#L7

`npm start` immediately consumes an extra 40-50MB of ram, and never releases it. This is about 10% of the memory capacity of the 1x Standard Dyno.

Perhaps we can just call `node server.js` directly, by default.

**Comment by hunterloftis** [comment]
One of the primary goals of the buildpack is to prevent lock-in / Herokuisms. I'd like to keep things as useful for the OSS community as possible by integrating with standard workflows (like `npm start`). 

That said, you can already run `node server.js` without loading npm by adding a Procfile to your app:

```
web: node server.js
```

When both a Procfile and a start script exist, the Procfile takes precedence.

**Comment by tjwebb** [comment]
> When both a Procfile and a start script exist, the Procfile takes precedence.

Right, but because the default is `npm start` regardless of NODE_ENV, this caveat should at least be documented. I wrote an article on this the other day, but I haven't found much other literature on the topic: https://medium.com/@tjwebb/the-npm-start-default-uses-a-lot-of-ram-3e0d8ac0c6a1#.mpaagh2gg
