### ISSUE TITLE
Modify .npmrc to let proxies work?

### ISSUE THREAD

**Issue by davidjahn** [heroku/heroku-buildpack-nodejs#303]
Hi,

When staging an app with the `http_proxy` and/or `https_proxy` environment variables set, it looks like `npm` does not use the proxy during staging, and will only download dependencies through the proxy if an app's `.npmrc` file contains, e.g., `proxy=http://proxy.example.com`.

We are planning to modify `bin/compile` in the Cloud Foundry Node.js buildpack (which [is forked](https://github.com/cloudfoundry/nodejs-buildpack) from the Heroku buildpack) to add the needed lines to `.npmrc` if `http_proxy` / `HTTP_PROXY` / `https_proxy` / `HTTPS_PROXY` are set as environment variables by a user. This would let the buildpack stage properly, e.g., from behind a corporate proxy. Would it be a useful/welcome PR if we submitted this change upstream here?

**Comment by hunterloftis** [comment]
Thanks for offering to upstream!

By 'staging' do you mean running `npm install`?

Could you link me to the issue regarding npm not pulling proxy info from the environment? I would expect this to work:

```
$ NPM_CONFIG_HTTPS_PROXY=foo npm install
```

Or, on Heroku:

```
$ heroku config:set NPM_CONFIG_HTTPS_PROXY=foo
```

**Comment by davidjahn** [comment]
@hunterloftis Yes, by staging I mean the `npm install` command the buildpack runs.

There is no current issue. We were testing each buildpack's ability to use a proxy with only the `http_proxy` and `https_proxy` environment variables set, as this is the most common way people set proxies. It happened that all other buildpacks "just use" the proxy with no other modifications necessary.

Basically we are trying to prevent unexpected behavior when a user, e.g., tries

```
$ heroku config:set HTTP_PROXY=foo
$ heroku config:set HTTPS_PROXY=foo
$ heroku push my-app
```

Do you think it would be reasonable default behavior for the `bin/compile` script to set `NPM_CONFIG_HTTPS_PROXY` equal to `HTTPS_PROXY` or `https_proxy` if those environment variables are defined?

**Comment by hunterloftis** [comment]
I see, thanks for clarifying.

According to [their docs](https://docs.npmjs.com/misc/config#https-proxy), npm should already respect `HTTP_PROXY` and `HTTPS_PROXY`. Might be a good idea to ask @othiym23 if they're aware of the issue.

**Comment by davidjahn** [comment]
Yep, saw that doc as well. Our observation was that these environment variables were not respected by npm when an app is pushed with default versions (our fork defaults to node 0.12.9 and npm 2.14.9).

Not sure if this is before they added support for those env variables, or if the support is broken. I'll try to double-check the issue.

**Comment by davidjahn** [comment]
Hey, I am closing this issue because we determined that our version of npm reads `HTTP_PROXY` and `HTTPS_PROXY` as you indicated. We were seeing problems with npm talking successfully to the proxy, which would be an issue for npm, not here. Thanks, and sorry for the confusion!

**Comment by hunterloftis** [comment]
@davidjahn thanks for posting the update and shepherding the issue!
