### ISSUE TITLE
Unbuilds then immediately rebuilds `devDependencies`

### ISSUE THREAD

**Issue by kevinburkeshyp** [heroku/heroku-buildpack-nodejs#304]
Hi,
To avoid problems/errors/transitive build failures with dev dependencies, we check them into our shrinkwrap file. However, this means our dev dependencies get pruned and then immediately reinstalled as part of the build process:

```
install_node_modules() {
  local build_dir=${1:-}

  if [ -e $build_dir/package.json ]; then
    cd $build_dir

    echo "Pruning any extraneous modules"
    npm prune --unsafe-perm --userconfig $build_dir/.npmrc 2>&1
    if [ -e $build_dir/npm-shrinkwrap.json ]; then
      echo "Installing node modules (package.json + shrinkwrap)"
    else
      echo "Installing node modules (package.json)"
    fi
    npm install --unsafe-perm --userconfig $build_dir/.npmrc 2>&1
  else
    echo "Skipping (no package.json)"
  fi
}
```

Any ideas for a workaround? I'm a little reluctant to _not_ check in `devDependencies`, though maybe it's unnecessary

**Comment by hunterloftis** [comment]
So you mean you're tracking `devDependencies` in git?

Could you provide a little more detail about the issues you were seeing beforehand, with shrinkwrapped deps?

**Comment by kevinburkeshyp** [comment]
I guess we just have a fair number of packages in our `devDependencies`, and I'd rather not track down "dev dependency A is broken because it depends too loosely on dependency B, which upgraded" errors - roughly the same reason we shrinkwrap our production dependencies.

We shrinkwrap both the devDependencies and the prod dependencies, and track `npm-shrinkwrap.json` in Git, but we don't check our node_modules folder into git.

**Comment by hunterloftis** [comment]
pushing shrinkwrap issues to the back of the queue since yarn is a much better deterministic build solution.

**Comment by kevinburkeshyp** [comment]
Agreed
