### ISSUE TITLE
Provide smart defaults for garbage collection flags

### ISSUE THREAD

**Issue by hunterloftis** [heroku/heroku-buildpack-nodejs#309]
Eg, automate this somewhat: https://blog.heroku.com/archives/2015/11/10/node-habits-2016#7-avoid-garbage

One idea is here: https://github.com/bjfletcher/node-memory-behaviour - essentially, provide a `$NODE_FLAGS` env var from profile.d (similar to `$WEB_CONCURRENCY`) that can be used when invoking the `node` runtime. Opt-in, no side-effects. Can be used in other binaries as well (`iojs`, `slc`, etc).

**Comment by danielleadams** [comment]
Going to close this since Node 12 doesn't require manually specifying available memory anymore. Some of the other flags may still be needed, but we can open another issue if it the issue comes up again.
