### ISSUE TITLE
Increase default retries config

### ISSUE THREAD

**Issue by hunterloftis** [heroku/heroku-buildpack-nodejs#311]
To address some of the `ECONNRESET` issues with keeping in touch with the npm registry:
- https://docs.npmjs.com/misc/config#fetch-retries

The buildpack could increase the default `NPM_CONFIG_FETCH_RETRIES` from 2 to, say, 10.

**Comment by jmorrell** [comment]
Closing this since this hasn't been really an issue. Will reopen if we start seeing this come up again.
