### ISSUE TITLE
Set `NPM_CONFIG_PROGRESS=false` to speed up npm install

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-nodejs#312]
The npm progress bar slows down npm install considerably on certain versions of npm (see https://github.com/npm/npm/issues/11283). Whilst some of the root causes have PRs in their respective upstream npm modules, not all of these have made it into the latest npm release (as far as I can tell) - and even when they do, it still won't help older versions of npm.

As such, I think this buildpack should define `NPM_CONFIG_PROGRESS=false` prior to its `npm install` invocations to speed up the compile step. (After all, the progress bar is pointless for the build log output anyway.)

I'm happy to open a PR if this change will be accepted? :-)

**Comment by hunterloftis** [comment]
Npm only shows a progress bar on interactive ttys. The output stream from a git push isn't interactive, so there's no progress bar (or slowdown).

**Comment by edmorley** [comment]
Ah true :-)
