### ISSUE TITLE
Retry if logs suggest an intermittent npm issue

### ISSUE THREAD

**Issue by hunterloftis** [heroku/heroku-buildpack-nodejs#315]
For instance, npm occasionally fails with "ECONNRESET" and "Callback called more than once." Perhaps restart the buildpack if certain strings are seen in the output stream?

**Comment by hunterloftis** [comment]
- https://github.com/npm/npm/issues/9418
- https://github.com/npm/npm/issues/12484
- https://github.com/npm/registry/issues/10

**Comment by szarouski** [comment]
You might want to give https://github.com/jfromaniello/npm-install-retry/issues/7 a try

**Comment by hunterloftis** [comment]
Thanks for the link @szarouski!

**Comment by jmorrell** [comment]
Closing this since it seems to be less of an issue now. I'll revisit if it starts coming up again.
