### ISSUE TITLE
Build node app that's not in the root directory

### ISSUE THREAD

**Issue by woniesong92** [heroku/heroku-buildpack-nodejs#323]
I read the discussions at #192 and #203 and I have questions.

I have a rails app that lives in `/` and a node app in `/front`. The rails app will serve as an API server and the node app as a frontend server that will be the entry point for the users.

My plan was using the multi-buildpack and include ruby and nodejs buildpacks. But since my node app doesn't live at `/`, Heroku rejects my push because it cannot find `package.json` at `/`. I can possibly work around this by having an empty `/package.json` but then I would have to set caching directories.

What might be the cleanest solution for me?

**Comment by andyweiss1982** [comment]
For what it's worth I am super curious about the answer to this.  @woniesong92 have you discovered anything yet?

**Comment by woniesong92** [comment]
Your best bet is just use `runit` to start multiple web servers on one Heroku dyno. But that solution ends up making the deployment process ugly because of other complications. Instead of trying to solve everything, I ended up dedicating one Heroku dyno for one web server.

**Comment by hunterloftis** [comment]
I agree it would be nice to have the capability of pointing the buildpack to a non-root directory. This isn't a high priority compared to the rest of the buildpack work, especially given that the existing solution is not difficult (package.json in root). If someone wants to open a PR, I'll review it. Tests and minimal impact to the existing codebase are crucial.

**Comment by andyweiss1982** [comment]
Thanks @hunterloftis...  Is the recommended implementation then to just place an empty package.json with {} at root, or should certain values be set (build_dir? cache_dir?).

**Comment by hunterloftis** [comment]
If you're trying to build, for example, an app that only exists in ./client, you can use something like this:

```json
"scripts": {
  "postinstall": "cd client && npm install"
}
```

**Comment by andyweiss1982** [comment]
that is awesome -- thanks!

**Comment by dreyks** [comment]
@hunterloftis I got up with the same solution, but this results in root `node_modules` folder being empty and the real folder not being cached

**Comment by hunterloftis** [comment]
@dreyks you can cache arbitrary directories as well: https://devcenter.heroku.com/articles/nodejs-support#custom-caching
