### ISSUE TITLE
Procfile content ignored upon deploy

### ISSUE THREAD

**Issue by kaytrance** [heroku/heroku-buildpack-nodejs#330]
I have a `Procfile` in my app directory having `web: sails lift --verbose`. I am hosting my app on digitalocean with dokku. When I deploy an app I can clearly seen that `Procfile` is ignored and `npm start` is running instead.

Why?

**Comment by hunterloftis** [comment]
The buildpack doesn't generate a Procfile or use one in any way (other than warning if one is missing). The running platform (Heroku's Cedar-14 stack or, in your case, dokku on digitalocean) is responsible for respecting the Procfile behavior.
