### ISSUE TITLE
Consider no default cache when npm-shrinkwrap exists

### ISSUE THREAD

**Issue by hunterloftis** [heroku/heroku-buildpack-nodejs#332]
Since users with npm-shrinkwrap checked in are ostensibly wanting deterministic builds, and locally may be running `rm -rf node_modules && npm install`, it may be a good idea to default the cache to false when shrinkwrap is detected.

Alternatively, as a softer option, we could add a warning to builds that have both an active node_modules cache and an npm-shrinkwrap file.

**Comment by itaysabato** [comment]
What is actually the problem with using shrinkwrap together with caching? Could it be that caching is made without referring to the shrinkwrap file or to the actual modules that were installed?

I am experiencing a strange behavior using `npm-shrinkwrap` (even without caching) - the build log reports the wrong dependency tree at the end of the build and claims I have unmet dependencies even though the app clearly works fine after the deployment.

Interestingly, if I disable caching I then get the correct tree, followed by the wrong tree with the warning, e.g.
```
-----> Node.js app detected
-----> Creating runtime environment

       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=false
       NODE_ENV=production
       NODE_MODULES_CACHE=false
-----> Installing binaries
       engines.node (package.json):  6.9.1
       engines.npm (package.json):   3.10.8
       
       Downloading and installing node 6.9.1...
       npm 3.10.8 already installed with node
-----> Restoring cache
       Skipping cache restore (disabled by config)
-----> Building dependencies
       Installing node modules (package.json + shrinkwrap)

...yada yada...

<Good Tree>

-----> Caching build
       Clearing previous node cache
       Skipping cache save (disabled by config)
-----> Build succeeded!

<Wrong Tree>

 !     Unmet dependencies don't fail npm install but may cause runtime issues
       https://github.com/npm/npm/issues/7494

...yada yada...
```

Any insights into why this is happening are welcome...

Thanks.

**Comment by hunterloftis** [comment]
Going to push shrinkwrap issues to the back of the queue since yarn is a much better solution anyway.

**Comment by itaysabato** [comment]
@hunterloftis in what "queue" exactly do you keep closed issues? Seems more like you decided that people who use shrinkwrap should not get any support...

With all due respect :)

**Comment by renatoargh** [comment]
For those who still need to disable cache permanently or temporary:

```bash
heroku config:set NODE_MODULES_CACHE=false
git commit -am 'rebuild' --allow-empty
git push heroku master
heroku config:unset NODE_MODULES_CACHE
```
