### ISSUE TITLE
How to use this buildpack for NodeJS workers

### ISSUE THREAD

**Issue by adambuczynski** [heroku/heroku-buildpack-nodejs#335]
Hello, I'm trying to setup a worker Dyno as per https://devcenter.heroku.com/articles/procfile#process-types-as-templates, and I have created a Procfile with the following:

```
worker: node app/index.js --mock
```

However, when I deploy to Heroku it fails to run because it's still trying to run `npm start` because that's configured in this build pack as the default process.

How do I stop it from running the default? I thought explicitly declaring a process type and command in the Procfile would be sufficient.

Do I really have to clone this repository and change the default process just to spin up a NodeJS worker dyno?

**Comment by hunterloftis** [comment]
The buildpack sets default process types when a Procfile isn't provided, but has nothing to do with setting or scaling any of those process type instances at runtime.

By default, new apps run with the `web` process type. To start a worker instead, scale web down and worker up:

```
$ heroku scale web=0 worker=1
```

**Comment by adambuczynski** [comment]
Hmm, I would assume that the build process would be smart enough to detect this, at least for first run, and to discover that I have defined a non-web process in my Procfile, and scale it accordingly. Thanks.

**Comment by hunterloftis** [comment]
The build process has nothing to do with runtime - its job is to build a slug (essentially, a tarball of all the files needed to run your app). So the output of the build process is just a file system.

At runtime, whatever runtime is being used (for instance, on Heroku it's Cedar-14), is responsible for executing processes in that filesystem. The execution is what costs resources (and money), so by default only `web` is started unless the user explicitly scales a process up (indicating that he or she does want that process to be running and billing). More info here:

- https://devcenter.heroku.com/articles/procfile#scaling-a-process-type
