### ISSUE TITLE
Wrong Node version

### ISSUE THREAD

**Issue by stoplion** [heroku/heroku-buildpack-nodejs#336]
Not sure if this is a buildpack problem or not, but appears like Heroku is using the wrong Node even though correct binary was installed..

Specify correct Node version..

```
"engines": {
    "node": "6.5.0",
    "npm": "3.10.3"
  },
  "scripts": {
    "postinstall": "node_modules/gulp/bin/gulp.js buildProd",
    "start": "node server.js -p $PORT"
  }

```

When deploying, the log is shown..

```

-----> Installing binaries
remote:        engines.node (package.json):  6.5.0
remote:        engines.npm (package.json):   3.10.3
So Heroku appears to be picking up on the engine field of package.json and installing the correct version.
```

But when checking Node version on Heroku...

```
heroku run bash
Node -v
v0.10.30
```

[orig SO question](http://stackoverflow.com/questions/39482502/heroku-stuck-at-node-v0-10-30-but-package-json-asks-for-current-version)

**Comment by hunterloftis** [comment]
If this is a multibuildpack app, be sure to put node first (otherwise ruby will install an older default).
