### ISSUE TITLE
Allow overriding LOG_FILE env var

### ISSUE THREAD

**Issue by sandfox** [heroku/heroku-buildpack-nodejs#340]
Before I embark on a PR for this...
I'd like to allow the `LOG_FILE` env var to be set externally to the `compile` script so that compile script will use it if it's already set, otherwise falling back to it's current setting.

e.g psudo-code (because I can't remember the bash for this...)

```
LOG_FILE = LOGFILE || '/tmp/node-build-log.txt'
```

**Comment by hunterloftis** [comment]
I'd merge a PR with this functionality.

**Comment by jmorrell** [comment]
Closing as there hasn't been interest in this for some time. If this is still something you'd like to see please give me a use case and I'll reopen.
