### ISSUE TITLE
Node binary cache

### ISSUE THREAD

**Issue by freddi301** [heroku/heroku-buildpack-nodejs#346]
Please add node binary cache.
When building with buildpack on cloud, downloading always the node binary is not an issue,
but using the buildpack locally is not feasible due to ~5minutes waiting the node binary downloads again.
Reading the code there is no attempt to do this, it just downloads node anew

**Comment by hunterloftis** [comment]
I don't expect I'll do this (as the node buildpack is, after all, designed for cloud services). However, how would you suggest implementing such a cache?

**Comment by freddi301** [comment]
Hi,
I was thinking that you could save the downloaded zip not as ```/tmp/node.tar.gz``` but ```/tmp/node-v$version-$os-$cpu.tart.gz``` and in the next installation just check if the file is available locally, if not download;
Or just save the string of the last downloaded node version and if different on next installation -> download, use existing otherwise.
AFAIK the buildpack is used in separate containers so the second more simple approach could work, even without adding checksum control.
This could apply to yarn and others too.
I update a lot the heroku dyno on staging to do acceptance tests, the node binary is about ~100mb, this could save some bandwidth

**Comment by hunterloftis** [comment]
Introducing state (especially binary blobs) into the node buildpack is something I'd prefer to avoid. If we can come up with a clean way to do it that doesn't increase the complexity of the buildpack (like checking multiple local / remote places for a node binary would), that might work.

**Comment by freddi301** [comment]
The directories used for node_modules could be the place

**Comment by hunterloftis** [comment]
What makes more sense than putting a binary caching layer in the buildpack, if you're interested in running the buildpack locally in a place with a bad network connection where it takes so long to download bins, is to set up a local network cache in that environment:

- https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Storage_Administration_Guide/ch-fscache.html

**Comment by jmorrell** [comment]
Closing this as I'm not interested in adding state like this to the buildpack

**Comment by aleclarson** [comment]
I think there's plenty of convenience in caching the binary locally, especially for poor internet speed and working on a limited cellular data plan. Another use case is faster iteration when using the buildpack with vagrant. As for setting up a local network cache, I would argue baking the caching layer into the buildpack is much easier for people looking for a quick fix without the unnecessary learning curve.

Thoughts on creating a separate branch for those who want a caching layer?

**Comment by jmorrell** [comment]
@aleclarson This isn't really a priority for Heroku customers since we download the binary on the dyno and not locally. However if you make a branch that works well I would consider merging it. 

The feature makes sense, but comes with additional complexity that will need to be handled by support and will have ongoing costs to Heroku.

This is where I would start looking: https://github.com/heroku/heroku-buildpack-nodejs/blob/master/lib/binaries.sh#L48

**Comment by aleclarson** [comment]
@jmorrell There aren't any Heroku customers that test locally with `vagrant` and something like Dokku?
