### ISSUE TITLE
Builds failing for project that uses yarn

### ISSUE THREAD

**Issue by joshwcomeau** [heroku/heroku-buildpack-nodejs#350]
Hey guys!

So a few hours ago, our builds started failing. Some digging shows that packages weren't getting installed.

The packages in question were sub-sub-dependencies, and seemingly random.

We use Yarn locally, and `yarn install` catches them. They're indexed in our local yarn lockfile.

When deploying, though, these dependencies aren't included, and webpack fails to build with `module not found` errors.

The packages in question were `sax` and `has`. For `sax`, it was linked through a couple other dependencies to `css-loader`.

I know this probably isn't enough info to go on, but I'm not sure what else to provide. Let me know if I can do anything else to help debug!

**Comment by hunterloftis** [comment]
Hey @joshwcomeau, thanks for letting us know - would you mind opening a ticket, referencing the specific app, checking "allow access," and and mentioning this GH issue so I can check it out?

**Comment by joshwcomeau** [comment]
Done - ticket #433057

**Comment by DavidJFelix** [comment]
This is happening for me as well. It appears that the nodejs buildpack isn't picking up my devDependencies correctly, so when I'm using create-react-app it isn't able to run the react scripts. When I removed the `yarn.lock` file, this buildpack went back to the npm behavior and it works fine.

Here's the commit that took my build from failing to building: https://github.com/mg4tv/mg4tv-web/commit/e8e2f0af79ff97bfb0b3b8683a98d9ddfb280b4b

@joshwcomeau good to see you again.

**Comment by taylorqj** [comment]
Confirming this an issue for me, it also seems completely random on sub dependencies. I can post additional logs if it's helpful.

```bash
-----> Building dependencies
       Installing node modules (yarn)
       yarn install v0.18.1
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       warning fsevents@1.0.14: The platform "linux" is incompatible with this module.
       info "fsevents@1.0.14" is an optional dependency and failed compatibility check. Excluding it from installation.
       [3/4] Linking dependencies...
       [4/4] Building fresh packages...
       error /tmp/build_4a71881a0260e535f8d36cf11cdc9eb0/NAME-OMITTED-3419183344a29e4c857b3a5197969481bdb0f4a9/node_modules/node-sass: Command failed.
       Exit code: 1
       Command: sh
       Arguments: -c node scripts/install.js
       Directory: /tmp/build_4a71881a0260e535f8d36cf11cdc9eb0/NAME-OMITTED-3419183344a29e4c857b3a5197969481bdb0f4a9/node_modules/node-sass
       Output:
       module.js:471
       throw err;
       ^
       
       Error: Cannot find module 'is-fullwidth-code-point'
       at Function.Module._resolveFilename (module.js:469:15)
       at Function.Module._load (module.js:417:25)
       at Module.require (module.js:497:17)
       at require (internal/module.js:20:19)
       at Object.<anonymous> (/tmp/build_4a71881a0260e535f8d36cf11cdc9eb0/NAME-OMITTED-3419183344a29e4c857b3a5197969481bdb0f4a9/node_modules/string-width/index.js:4:28)
       at Module._compile (module.js:570:32)
       at Object.Module._extensions..js (module.js:579:10)
       at Module.load (module.js:487:32)
       at tryModuleLoad (module.js:446:12)
       at Function.Module._load (module.js:438:3)
       info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
-----> Build failed
```

**Comment by tribou** [comment]
Hit this issue as well.

For anyone else searching, I found a couple workarounds until this issue gets fixed:

- Add `yarn.lock` to a [`.slugignore` file](https://devcenter.heroku.com/articles/slug-compiler#ignoring-files-with-slugignore) so Heroku goes back to using NPM for now. (solution I chose)

OR

- Set your buildpack to the [last working version](https://devcenter.heroku.com/articles/nodejs-support#build-behavior) with `heroku buildpacks:set https://github.com/heroku/heroku-buildpack-nodejs#v91`

**Comment by hunterloftis** [comment]
Yarn is not a drop-in npm equivalent. It's close, but not quite. So it's very possible that you'll need to edit your project somewhat for full compatibility with yarn.

One example of this is the `devDependencies` mentioned above. Yarn doesn't yet respect `NPM_CONFIG_PRODUCTION`, but instead looks at `NODE_ENV` and `YARN_PRODUCTION` to determine whether or not to install `devDependencies`.

If you want to have a `yarn.lock` file but opt out of using yarn, you can:

- https://devcenter.heroku.com/articles/nodejs-support#build-behavior

**Comment by hunterloftis** [comment]
https://github.com/heroku/heroku-buildpack-nodejs/issues/359

**Comment by PaulieScanlon** [comment]
Hi, bit late to the party but.... if anyone else experiences problems with Heroku and node-sass the solution that worked for me was to add a .slugignore file to the root of my project, add /yarn.lock to the .slugignore file and add "postinstall": "npm rebuild node-sass" to scripts in package.json.

**Comment by jeanniton-mnr** [comment]
**Issue**

Heroku needs to know what version of Yarn to download for any app that is deployed on our platform. The convention is to specify a version requirement in the engines field of package.json.

```
{
  "name": "myapp",
  "description": "a really cool app",
  "version": "1.0.0",
  "engines": {
    "node": "12.10.0",
    "yarn": "1.19.1"
  }
}
```
However if a version is specified that has no matching version of Yarn then the build prints a warning and fails.

**Resolution**
Heroku recommends specifying the exact version of Yarn that you are using locally in the engines field. To find your version locally:

```
$ yarn --version
1.19.1
```

[](https://help.heroku.com/8MEL050H/why-is-my-node-js-build-failing-because-of-no-matching-yarn-versions)
