### ISSUE TITLE
Cannot resolve private dependencies using yarn

### ISSUE THREAD

**Issue by vhuerta** [heroku/heroku-buildpack-nodejs#357]
Hi, i just commited my yarn.lock file to my repo and now is being builded with yarn, but when yarn try to resolve a private repo it fails, i'm setting a .npmrc file with the authentication token, this was working with npm, can you tell me if with yarn there's another way to make it work?

Here's my trace:

```
error An unexpected error occurred: "https://registry.yarnpkg.com/@private/dependency/-/dependency-0.0.4.tgz: Request failed "404 Not Found"".
```

Best regards

**Comment by kazkovsky** [comment]
Look at my issue here: https://github.com/heroku/heroku-buildpack-nodejs/issues/358
There is heroku-prebuild hook that saves .npmrc file with NPM_TOKEN from app ENV settings.

**Comment by hunterloftis** [comment]
Yarn is a new technology and does not have full feature parity with npm. If you want to have a `yarn.lock` but still build with npm, you can opt out:

- https://devcenter.heroku.com/articles/nodejs-support#build-behavior
