### ISSUE TITLE
Failing build angular2 app on rails

### ISSUE THREAD

**Issue by stephenarifin** [heroku/heroku-buildpack-nodejs#362]
Hey guys,

I am trying to deploy an angular2 app on rails onto heroku and cannot get it to build. The build always crashes at the same place and the error message is extremely arbitrary.

Here is my package.json

{
  "name": "client",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "preinstall": "npm install -g http-server",
    "postinstall": "ng build -prod",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "core-js": "^2.4.1",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2",
    "@angular/compiler-cli": "^2.3.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.24",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.0.2",
    "typescript": "~2.0.3"
  },
  "engines": {
    "node": "6.9.3",
    "npm": "3.10.10"
  }
}

remote:        > client@0.0.0 postinstall /tmp/build_b79a1a95f91c2b5fc0c2a4212cc771d7/client
remote:        > ng build -prod
remote:                                34% building modules 202/320 mo/app/tmp/buildpacks/1b833af07673c7f3f592862588092f5cabc79cc267fde671a34ceabbd900d03ae630e46e45c8a30fb2deebbc07cf763332dc2bde1955af016a78de5d1b1be763/lib/output.sh: line 11: echo: write error: Resource temporarily unavailable
remote: 
remote: -----> Build failed
remote:        
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:        
remote:        If you're stuck, please submit a ticket so we can help:
remote:        https://help.heroku.com/
remote:        
remote:        Love,
remote:        Heroku
remote:        
remote:  !     Push rejected, failed to compile Node.js app.
remote: 
remote:  !     Push failed
remote: Verifying deploy....
remote: 
remote: !       Push rejected to obscure-coast-44209.

I'm extremely frustrated and could use any advice please! If you need anymore information please let me know.

**Comment by hunterloftis** [comment]
Based on this: `remote: 34% building modules 202/320`, are you perhaps running webpack with the `--progress` flag? Webpack has a bug in that it will spew hundreds of thousands of characters out onto a single line even on a non-TTY terminal (most modules check for TTY before outputting progress bars, but webpack does not).

If that's the case, remove `--progress` to avoid overflowing the output buffer.

**Comment by jmorrell** [comment]
👋 Hi @stephenarifin,

I'm taking over the nodejs buildpack as a new maintainer and cleaning out issues. If this is still an issue for you, please open a support ticket at https://help.heroku.com/, and I'll be happy to assist you over there :)
