### ISSUE TITLE
Incorrectly caching NPM modules installed from github 

### ISSUE THREAD

**Issue by ThariqS** [heroku/heroku-buildpack-nodejs#364]
When I install a package from Github like so:

`"packagea": "github:org/packageA#master",`

Heroku will cache this package and keep using the same version, even if I submit a new commit with a new package.json version to the packageA repo. The only way I can find around this is to use heroku-repo to destroy the entire cache before every deploy.

Some context, I'm doing this within the context of lerna.js (https://lernajs.io/) so that I'm working on multiple packages at once, using npm link to get live code. Then when deploying, I deploy all of the changed packages with updated package.jsons to github and finally deploy my app to Heroku which uses those packages as dependencies. As far as I can tell this is not a race condition, and heroku continues the cache even half an hour after the intial deployment.

**Comment by ThariqS** [comment]
Was wondering if you guys had any idea about this? I'm happy to submit a PR if you have a general sketch of where I might look. Otherwise, is this not the right place?

**Comment by hunterloftis** [comment]
This is how npm works... if the package already exists, from github, it's just used. Github packages don't get the benefit of things like semver checking (since they're just urls). You'll see the same thing locally unless you regularly clear out your local `node_modules` dir.

To get fresh packages from a github master branch just disable caching:

```
$ heroku config:set NODE_MODULES_CACHE=false
```

**Comment by jmorrell** [comment]
Closing this out as this is more of an issue for npm than the buildpack. There is some discussion on the npm repo here: https://github.com/npm/npm/issues/4191 but there doesn't seem to have been any recent movement :(

In the meantime, disabling the cache as @hunterloftis suggested should solve the immediate problem.
