### ISSUE TITLE
build failure due to `yarn check`

### ISSUE THREAD

**Issue by aliceriot** [heroku/heroku-buildpack-nodejs#367]
Hey y'all,

Last night we began experiencing build failures on the nodejs buildpack due to `yarn check` not passing. It looks like this change is involved: https://github.com/heroku/heroku-buildpack-nodejs/commit/06f23f2e42644975267f827f4b8e29b18c35d628#diff-b796d034e8c512aaeb727f89e3598620R32

Our application depends on [Searchkit](https://github.com/searchkit/searchkit), a set of React components for building search UIs for elasticsearch. Searchkit has a peer dependency of `react@^0.14.7`, and we use `react@15.4.1` for our application. We use an alias in our webpack configuration to ensure that `import React from 'react'` will resolve to only the version we specify.

The problem is that the mismatch between the peer dependency that Searchkit specifies and the version we specify causes `yarn check` to fail:

```
$ yarn check --no-progress
yarn check v0.18.1
warning fsevents@1.0.15: The platform "linux" is incompatible with this module.
info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
error "searchkit-multiselect#react@0.14.x" doesn't satisfy found match of "react@15.4.1"
error "searchkit-multiselect#searchkit@0.9.x" doesn't satisfy found match of "searchkit@0.10.0"
error "searchkit#history" is wrong version: expected "2.1.2", got "2.1.1"
error Found 3 errors.
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
```

Would it be possible to add an environmental variable that disables the `yarn check` step in the build? In this case we're aware of the discrepancy, but we know that our app builds and boots just fine with it. Without a way to disable the check deploys are broken for us until we either fork Searchkit or the Searchkit devs update their dependencies.

The code for the app in question is here: https://github.com/mitodl/micromasters if you want to look at a `package.json` / `yarn.lock` combo for repro purposes. We're using `yarn@0.18.1` currently.

Thanks for reading!

**Comment by hunterloftis** [comment]
Thanks for the great issue report!

We added `yarn.check` essentially to check for folks who have accidentally added a yarn.lock file that they aren't using anymore, but still have it checked in.

How's this for a fix?
https://github.com/heroku/heroku-buildpack-nodejs/pull/366/commits/5018f519779078a220f3ab3624ac64b4c1c64768

That should notify users who are mistakenly using yarn, or have forgotten to update their lock file, without automatically failing the build.

**Comment by aliceriot** [comment]
That looks fantastic!

**Comment by michaek** [comment]
That seems like it should at least not fail the build, but it may be that `yarn check` is doing more than we want? `yarn check --integrity` succeeds in cases that `yarn check` does not, though the documentation isn't very clear about the reasoning for increased strictness.

**Comment by hunterloftis** [comment]
@michaek I'd be interested in knowing the differences; the docs also don't mention that `yarn check` will fail if `node_modules` aren't actually installed, suggesting instead that it just compares package.json to yarn.lock.

**Comment by toverux** [comment]
With `--integrity` or not, a build failure is too strict.

The two errors I have when I run `yarn check`: 

```
error "watch-ignore-webpack-plugin#webpack@1.5.x" doesn't satisfy found match of "webpack@2.2.0"
error "\u001b[2mpostcss-merge-rules#\u001b[22mbrowserslist" is wrong version: expected "1.6.0", got "1.7.0"
```

(Also fails with --integrity)

The first is an unmet peer dep that I'm aware of, but that works at runtime.
The second is not on my side, looks like a yarn bug or something.

**Comment by michaek** [comment]
@hunterloftis What I was running into was a transitive dependency whose resolved (published) version string didn't match the version string specified as a dependency. It's a pretty old version, so there's no real path to fixing the mismatch. Maybe there's a good reason to keep informing us about the mismatch, but it may be sufficient to just say "yarn.lock and package.json are in agreement". I'm open to either.

**Comment by hunterloftis** [comment]
In general, when choosing between a build failure and a runtime failure, I prefer a build failure.

Long-term we'll probably want to allow configuration of build strictness so that users who want to opt-out of a strict check can (and then we can stop informing them that the strict check fails). Whenever I add a new config API I have to support it indefinitely, so I like to have good conversations about that before implementation :)

**Comment by aliceriot** [comment]
Thanks for the quick action on this! 💯 🎆 👍

**Comment by hunterloftis** [comment]
@aliceriot ⚡️ give it a shot now and let me know if you're good to go? Quick test on my end with an intentionally bad package.json is working.

**Comment by aliceriot** [comment]
It looks like things are sorted! Thanks for your help 😄
