### ISSUE TITLE
Error on Downloading and installing node: gzip: stdin: unexpected end of file

### ISSUE THREAD

**Issue by ejust** [heroku/heroku-buildpack-nodejs#370]
Hello,

Since today, the buildpack construction is failing during nodejs installation.
If was try different nodejs versions, but I have the same error: **gzip: stdin: unexpected end of file**
For info, I use the PaaS Cloud Foundry Swisscom: Portal 3.5.4 - EXT API 3.5.4 - CF API 2.65.0

`=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-nodejs.git
=====> Detected Framework: Node.js
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  4.2.1
       engines.npm (package.json):   unspecified (use default)
       
       Downloading and installing node 4.2.1...
gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku`

Thank you 

Best regards,

Romain

**Comment by hunterloftis** [comment]
Failure levels are normal and I just tried building an app with several different node versions, all working.

My guess is there's an app issue - for instance, perhaps a config var set that interferes with `curl`. Please [open a ticket](https://help.heroku.com) so we can help you debug.

**Comment by ejust** [comment]
I don't think it's a problem with curl.
After the curl command, there is a test of return code 200 of curl.
`if [ "$code" != "200" ]; then
    echo "Unable to download node $version; does it exist?" && false
  fi`
So, I believe the download is OK. And, it's a problem after with the TAR command...

Nothing special was changed on the app side, also nothing on the cloud foundry application....
I will open a ticket to heroku and/or swisscom.

Thank you.
