### ISSUE TITLE
Should detect .heroku file, check for create-ability of .heroku/node

### ISSUE THREAD

**Issue by hunterloftis** [heroku/heroku-buildpack-nodejs#371]
If a user pushes a source tree that already includes .heroku/node, or which uses a file (vs dir) in .heroku, they get a cryptic error.

Instead, we should show a nice error like:

```
It looks like a ".heroku" file is checked into this project.
The Node.js buildpack uses ".heroku" to store binaries, like the node runtime and npm.
You should remove the .heroku file or ignore it by adding it to .slugignore
[link]
```

**Comment by jmorrell** [comment]
@hunterloftis Has this been an issue in the past? Is there a valid reason they would have the `.heroku` directory checked in?

**Comment by dzuelke** [comment]
I think I've hit this too for the PHP buildpack. People do all sorts of fascinating things :) The buildpack should definitely fail gracefully in this case.
