### ISSUE TITLE
Buildpack cache issue using yarn

### ISSUE THREAD

**Issue by Tonkpils** [heroku/heroku-buildpack-nodejs#372]
I'm not sure if this is the best place to file this issue and I'd be glad to move it to a more appropriate channel.

I recently switched a rails app to use yarn as our package manager from npm and I'm running into an issue where the first time I deploy (no cache), the build goes through fine along with the webpack postdeploy script finishing without any errors. However, the second time I deploy (using cache) there seems to be an issue with the cached node_modules which causes our webpack postdeploy script to fail. 

This is the output from the errors we receive from the postdeploy script.

```remote:        ERROR in ENOENT: no such file or directory, scandir '/tmp/build_e086571e173d417ec3d36623feb35cda/node_modules/node-sass/vendor'
remote:        @ ./~/@<private-org>/<repo>/lib/.../components/Layout/Layout.scss 4:14-121
remote:
remote:        ERROR in ENOENT: no such file or directory, scandir '/tmp/build_e086571e173d417ec3d36623feb35cda/node_modules/node-sass/vendor'
remote:        @ ./~/@<private-org>/<repo>/lib/res/styles/main.scss 4:14-113
remote:
remote:        ERROR in ./app/assets/javascripts/source/pages/.../.../image.png
remote:        Module build failed: Error: spawn /tmp/build_e086571e173d417ec3d36623feb35cda/node_modules/optipng-bin/vendor/optipng ENOENT
remote:        at exports._errnoException (util.js:1008:11)
remote:        at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
remote:        at onErrorNT (internal/child_process.js:348:16)
remote:        at _combinedTickCallback (internal/process/next_tick.js:74:11)
remote:        at process._tickCallback (internal/process/next_tick.js:98:9)
remote:        @ ./app/assets/javascripts/source/pages/users_orders/cart/app.cjsx 21:13-41
```

If it doesn't seem like an issue with the buildpack I'd be happy to close this. I'm going to try to debug this and any pointers on how to approach this would be great!

**Comment by hunterloftis** [comment]
I'm not sure if this is a buildpack issue, but if the first push is working for you, you might try disabling yarn's cache:

```
$ heroku config:set NODE_MODULES_CACHE=false
```

**Comment by Tonkpils** [comment]
Disabling the cache does work, however that doesn't seem like a good solution. It seems like it may be an issue with yarn? not sure but you're right I don't think this is a buildpack issue.

**Comment by jmorrell** [comment]
Hey @Tonkpils, I'm clearing out issues so I'm going to close this. If this is still a problem for you, could you file a ticket at https://help.heroku.com/? I'll get more information to help diagnose there, and I'll update the buildpack if it turns out we're doing something funky with the yarn cache.
