### ISSUE TITLE
Add ENV variable to turn on verbose mode for npm and yarn

### ISSUE THREAD

**Issue by samjbmason** [heroku/heroku-buildpack-nodejs#374]
It would be great if there was a way to get pass the `verbose` flag when deploying, to see why a build may be failing.

**Comment by hunterloftis** [comment]
Instead of building things like this into only the buildpack, it would be better to lobby for them in the yarn project. (for example, npm has `NPM_CONFIG_LOGLEVEL=verbose`). Once yarn can be set to verbose via an env var, it will automatically work on Heroku (and in any other environment).

**Comment by jmorrell** [comment]
I think adding an `NPM_LOGLEVEL` env variable to the buildpack that works with both `npm` or `yarn` is reasonable. The ability to do `NPM_CONFIG_*` for `npm` is more of an accident in how their config works.

**Comment by danielleadams** [comment]
Going to close this since there are verbose outputs for both:

NPM: https://docs.npmjs.com/misc/config#loglevel
Yarn 1: https://classic.yarnpkg.com/en/docs/cli/#toc-verbose

**Comment by swrobel** [comment]
> Yarn 1: [classic.yarnpkg.com/en/docs/cli/#toc-verbose](https://classic.yarnpkg.com/en/docs/cli/#toc-verbose)

@danielleadams I don't see how we can pass arbitrary flags to `yarn install` such as `--verbose`. How would we go about enabling verbose yarn output?
