### ISSUE TITLE
yarn > 0.16.1 cache directory change trouble

### ISSUE THREAD

**Issue by jordanh** [heroku/heroku-buildpack-nodejs#377]
When our application predeploy hook runs, we see:

```
 ./src/server/database/migrate.sh: line 59: /app/src/server/database/../../../node_modules/.bin/babel-node: No such file or directory
```

When I inspect the container, I see that files some of the files in app/node_modules are broken symlinks like:

```
lrwxrwxrwx 1  ... 107 Feb 23 23:24 babel-node -> ../../../../app/.cache/yarn/npm-babel-cli-6.18.0-92117f341add9dead90f6fa7d0a97c0cc08ec186/bin/babel-node.js
```

It appears as though it has something to do with an interaction between the buildback and the recent changes to where yarn stores its cache. When we pin the yarn version to `0.16.1` via `engines.yarn` in `package.json` everything works fine.

Is there something else we should try?

**Comment by hunterloftis** [comment]
The first thing to try is disabling caching altogether:

```
$ heroku config:set NODE_MODULES_CACHE=false
```

The next thing to try is using the latest version of yarn (yarn has a lot of bugs, but it's also fixing them at a rapid rate):

```json
"engines": {
  "yarn": "0.21.2"
}
```

**Comment by weyert** [comment]
I have tried `0.21.2` but didn't work for me. I keep getting odd errors which don't appear to happen with `0.16.1`. For example, that it can't find a random package similar to above.

**Comment by weyert** [comment]
Maybe it's' related to https://github.com/yarnpkg/yarn/issues/1275 ?

**Comment by jmorrell** [comment]
Hey @weyert, I'm clearing out issues so I'm going to close this. If this is still a problem for you, could you file a ticket at https://help.heroku.com/? I'll get more information to help diagnose there, and I'll update the buildpack if it turns out we're doing something funky with the yarn cache.
