### ISSUE TITLE
Could this tool specify subfolder location?

### ISSUE THREAD

**Issue by gamesover** [heroku/heroku-buildpack-nodejs#379]
I have a spa, backend is ruby on rails, front end is angular. I do need to build nodejs in client sub folder(not root path). But this tool does not support.

Kindly check https://github.com/gamesover/address-book-pwc and thanks for your help.

**Comment by jmorrell** [comment]
Hey @gamesover, sorry for the delay. I'm clearing out issues so I'm going to close this. If this is still a problem for you, could you file a ticket at https://help.heroku.com/? I'll get more information to help diagnose the issue there.
