### ISSUE TITLE
Error fetching buildpack

### ISSUE THREAD

**Issue by marcoippolito** [heroku/heroku-buildpack-nodejs#39]
buildpack for node.js cannot be fetched:

[ubuntu@ip-10-164-57-85:~/bitstarter]$git push staging-heroku staging:master
Counting objects: 456, done.
Compressing objects: 100% (323/323), done.
Writing objects: 100% (456/456), 259.62 KiB, done.
Total 456 (delta 122), reused 428 (delta 103)

-----> Fetching custom git buildpack... failed

 !     Push rejected, error fetching custom buildpack

To git@heroku.com:warm-oasis-1494.git
 ! [remote rejected] staging -> master (pre-receive hook declined)
error: failed to push some refs to 'git@heroku.com:warm-oasis-1494.git'

What do you suggest to do?

I reported the problem also in this thread where other people are encountering it:
https://github.com/kr/heroku-buildpack-go/issues/8#issuecomment-22268491

Looking forward to hear from you.
Marco

**Comment by hnk15** [comment]
> 
> 
> It looks like you're using a custom buildpack. If you're working on a Node.js app and would like to use the default heroku buildpack, unset the `BUILDPACK_URL` [config var](https://devcenter.heroku.com/articles/config-vars) and push again:
> 
> ```shell
> heroku config:unset BUILDPACK_URL -a <your-app-name-here>
> git push staging-heroku staging:master
> ```

Hi,
I have tried your solution but still i am getting the same error as bellow:

$ git push heroku master
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 4 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 352 bytes | 352.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote:  !     error fetching custom buildpack https://github.com/heroku/heroku-buildpack-nodejs.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to fathomless-mountain-32346.
remote:
To https://git.heroku.com/fathomless-mountain-32346.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/fathomless-mountain-32346.git'

please suggest any solution.

**Comment by lioneltuttle** [comment]
9 years later, it still doesn't work :)
