### ISSUE TITLE
Make Yarn Accessible to Script (without yarn.lock in root)

### ISSUE THREAD

**Issue by timscott** [heroku/heroku-buildpack-nodejs#402]
My app is client (React) and server (Rails), so I use this buildpack along with ```heroku/ruby```. The React app lives in the ```client``` folder. I have a ```package.json``` in the root for purposes of building, like so:

```json
  "scripts": {
    "build": "cd client && yarn && yarn run build && cd ..",
    "deploy": "cp -a client/build/. public/",
    "postinstall": "yarn run build && yarn run deploy && echo 'Client built!'"
  }
```

This fails because yarn is not found. A workaround is to add a dummy ```yarn.lock``` file to the root.

The workaround is fine, but in the interest of avoiding needless and confusing cruft, could there be a more explicit way to decide to make yarn available? I understand you don't want to download it every time.  Maybe specifying yarn in the engines?

**Comment by jmorrell** [comment]
This is reasonable. I've opened a PR to install yarn if it's defined in the engines.

**Comment by jmorrell** [comment]
This is now in production. You should have access to `yarn` :D
