### ISSUE TITLE
Add support for skipping heroku-postbuild when building for Heroku CI

### ISSUE THREAD

**Issue by simenbrekken** [heroku/heroku-buildpack-nodejs#412]
Large apps tend to transpile code, bundle assets etc. which makes for some extremely long build times. These tasks tend to be run by specifying a `postinstall/heroku-postbuild` script in `package.json`. 

When testing via Heroku CI this behavior can't disabled drastically slowing down tests as `postinstall/heroku-postbuild` is run before `npm run test`.

If there's no plans for this I'd be happy to contribute a PR. I'm thinking that `heroku-postbuild` (byt not `postinstall`) should be skipped when `NODE_ENV=test` and instead rely on `test-setup` to manually invoke something like `npm run heroku-postbuild/postinstall`

**Comment by rofrol** [comment]
Maybe set `env` and change `scripts`:

`"heroku-postbuild": "HEROKU_POSTBUILD && ./mybuild.sh"`
