### ISSUE TITLE
CI environment variables being overwritten

### ISSUE THREAD

**Issue by jmorrell** [heroku/heroku-buildpack-nodejs#414]
From: https://groups.google.com/a/heroku.com/forum/#!topic/heroku-ci-feedback/piO6y1cl9fo

> Hi, and thanks for providing a great CI service. I wasn't quite sure if I should put this up on the nodejs buildpack as an issue so I thought I'd try here first.
> It seems that the nodejs buildpack currently overwrites the environment of the test runner causing tests to be run with NODE_ENV=production:
> https://gist.github.com/simenbrekken/486e9e17cec07b31833b1071041ec69f
> If you look carefully, the CI runner is setting NODE_ENV=test, but then the nodejs buildpack is setting it back to production.

I'll look into this @simenbrekken

**Comment by henrikhaugboelle** [comment]
Hi @jmorrell, it seems that I'm running into this error. Are there any news on it? :-)
