### ISSUE TITLE
Yarn download mirror

### ISSUE THREAD

**Issue by nickstanish** [heroku/heroku-buildpack-nodejs#418]
It would be great to have some redundancy for the yarn binary in case yarnpkg.com is having issues (such as right now). Their binaries are also hosted on github so we could potentially check if the normal download fails, and try to download from https://github.com/yarnpkg/yarn/releases instead.

**Comment by fivetanley** [comment]
Thanks, we're discussing this internally also! We'll update when we have more information on what we'd like to do.

**Comment by jmorrell** [comment]
We've been working on an internal service for this, and it should be rolled out soon.

**Comment by Daniel15** [comment]
Rather than having to explicitly specify mirrors for all third-party downloads, it'd be good to have a caching reverse proxy if possible.

**Comment by akayvanfar** [comment]
yarnpkg.com down right now :(

**Comment by hchasey** [comment]
👍

**Comment by jmorrell** [comment]
It looks like yarnpkg.com was down for ~20 minutes.

Replacing this with an S3 mirror is my highest priority at the moment.

**Comment by Daniel15** [comment]
Yeah, sorry about the outage, it looks like this was some CloudFlare misconfiguration.

@jmorrell - Is it not possible to use a caching reverse proxy rather than a separate mirror?
