### ISSUE TITLE
Cannot fully disable Yarn cache

### ISSUE THREAD

**Issue by mgol** [heroku/heroku-buildpack-nodejs#419]
I have a Yarn project using `node-sass`. I've tried installing `node-sass` 4.5.3 before https://github.com/sass/node-sass/issues/1985 was closed and the `vendor` directory wasn't created properly, suggesting the compilation has failed:
```
remote:        ERROR in ./src/client/styles/styles.scss
remote:        Module build failed: ModuleBuildError: Module build failed: Error: ENOENT: no such file or directory, scandir '/tmp/build_RANDOM_HASH/node_modules/node-sass/vendor'
```

I'm not sure if that's expected but I thought I'll wait for the binaries to be generated and I'll try again. But when I pushed a new commit, I received the same error. This happens even though I have `NODE_MODULES_CACHE` set to `false`.

Isn't some cache still persisted?

**Comment by jmorrell** [comment]
For anyone arriving from google, the common solution to this error is to add the following entry to the `scripts` section in your `package.json`:

```
"postinstall": "npm rebuild node-sass"
```

However, with `NODE_MODULES_CACHE` set to `false` you shouldn't be seeing this error. There isn't any other cache that's saved. Can you open a help ticket at https://help.heroku.com/ ?

**Comment by mgol** [comment]
Thanks for the response; I opened a ticket.
