### ISSUE TITLE
gzip: stdin: not in gzip format

### ISSUE THREAD

**Issue by gabrielmancini** [heroku/heroku-buildpack-nodejs#44]
Hi Guys,

  I am trying upping the version of nodejs in heroku
  so following the steps to hack the buildpack, i made the necessary changes, but when i push the project the deploy show me this error:

```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Exiting with failure status due to previous errors

 !     Push rejected, failed to compile Node.js app
```

any one pass thru for this?

**Comment by volkanunsal** [comment]
Having the same problem today. Any update on this?

**Comment by volkanunsal** [comment]
If anyone is having the same problem, I ended up using version 63 and that worked well. 

```bash
heroku config:set "BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-nodejs#v63"
```

**Comment by hunterloftis** [comment]
@volkanunsal can you open a ticket (help.heroku.com) or paste your full output? It's difficult to figure out what's up without any context.

**Comment by hunterloftis** [comment]
I just did a quick search of our logs; the only instances of this error I see are people trying to install really old versions of Node (that we don't support anymore - like 0.6.11). I'll add some code to detect this either in semver or in the buildpack, but if you're specifying < 0.8.5 in package.json and you've found this thread - update your node engine! :)

**Comment by volkanunsal** [comment]
Nope, I'm using 0.11.33.

On Tue, Jan 13, 2015 at 2:20 PM, Hunter Loftis <notifications@github.com>
wrote:

> I just did a quick search of our logs; the only instances of this error I
> see are people trying to install really old versions of Node (that we don't
> support anymore - like 0.6.11). I'll add some code to detect this either in
> semver or in the buildpack, but if you're specifying < 0.8.5 in
> package.json and you've found this thread - update your node engine! :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/heroku-buildpack-nodejs/issues/44#issuecomment-69802355>
> .
>



-- 
*Volkan Unsal*
*web and mobile development*
volkanunsal.com <http://bit.ly/1h1ebjy>

**Comment by hunterloftis** [comment]
@volkanunsal I'm afraid I can't help if you won't give me any context!

**Comment by volkanunsal** [comment]
You're right. Huh. I guess it was always resolving to `0.10.35` before.

**Comment by hunterloftis** [comment]
Yeah #v63 always uses semver to resolve, while the later branches skip resolution if you specify an exact version (since we don't want to change versions on someone who is specifying exactly what they want).

**Comment by alexandre-mbm** [comment]
I found that I needed specify an old version for the node.

First I tried:
```json
"engines" : { "node" : "0.6.21" }
```

After:
```json
"engines" : { "node" : "0.8.5" }
```

**This worked:**
```json
"engines" : { "node" : "~0.8.5" }
```

**Comment by alexandre-mbm** [comment]
There are [nodejs.org/dist/v0.8.5](http://nodejs.org/dist/v0.8.5/) and [nodejs.org/dist/v0.6.21](http://nodejs.org/dist/v0.6.21/) but the first was OK for me.

**Comment by PanManAms** [comment]
I had this error twice today, but just pushing again works.

**Comment by hunterloftis** [comment]
@PanManAms likely means the node binary was unavailable initially and then became available.

I'll separate the download from the parsing so in between the two I can check whether or not the download succeeded.

**Comment by saru2020** [comment]
After so many years and still, this issue occurs.
Btw: My fix was to pin to a specific version as mentioned [here](https://elements.heroku.com/buildpacks/robgraeber/heroku-buildpack-nodejs-gulp):
`heroku buildpacks:set https://github.com/heroku/heroku-buildpack-nodejs#v75 -a my-app`
