### ISSUE TITLE
Requirement to create heroku-buildpacks-cf-nodejs

### ISSUE THREAD

**Issue by casibbald** [heroku/heroku-buildpack-nodejs#441]
With Google cloud functions using NodeJS as the language/framework base it has become necessary for "heroku-buildpacks-nodejs" to recognise when there is a serveless.yml file present in the root directory.

heroku-buildpacks-nodejs will now need to detect serveless.yml file and skip if found so as to allow heroku-buildpacks-cf-nodejs to run.

heroku-buildpacks-cf-nodejs ... to be submitted as a separate pull request.

**Comment by jmorrell** [comment]
Hi there 👋 

I doubt this is something we will support.

> With Google cloud functions using NodeJS as the language/framework base it has become necessary for "heroku-buildpacks-nodejs" to recognise when there is a serveless.yml file present in the root directory.

Why would this be the case? Wouldn't you also need a `package.json` to declare any dependencies for your script? Even if you were only using the Node stdlib, there's no harm in creating an empty `package.json` with just a name, which is all Heroku requires if you also have a `Procfile`.

```
{
  "name": "my-google-function"
}
```

Feel free to fork and modify the buildpack any way you like to meet your own needs, but this doesn't seem relevant for the vast majority of Node users on Heroku (at least not yet).
