### ISSUE TITLE
Call different postbuild / prebuild scripts during CI

### ISSUE THREAD

**Issue by clayne11** [heroku/heroku-buildpack-nodejs#443]
When running CI test, `heroku-postbuild` and `heroku-prebuild` are being called. When I build my app for deployment, however, the build is significantly different than building for tests.

We should call different build scripts for CI vs regular builds.

For example during CI we can call `heroku-test-postbuild` and `heroku-test-prebuild` and during regular builds we can can `heroku-postbuild` and `heroku-prebuild`. 

This gives users the ability to customize their CI vs regular build if necessary.

**Comment by jmorrell** [comment]
I'd prefer not the expand the surface area if we can avoid it. They're a bit confusing and, there's no taking them away once applications start depending on them, so they have to be carefully considered.

We (as well as other CI providers: Travis, CircleCI, etc) inject the environment variable `CI=true` to allow you to slightly modify your build scripts for CI workflows if needed. https://devcenter.heroku.com/articles/heroku-ci#environment-variables-env-key

This is how [create-react-app](https://github.com/facebookincubator/create-react-app) works by default for example: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/scripts/build.js#L126-L139

You can do this directly in your `package.json` script if you like by writing:

```
"heroku-postbuild": "[ $CI <> true ] && echo 'run ci build' || echo 'run normal build'"
```

Or you can factor it out into it's own bash script, node script, etc and use the environment variable there.

Previous discussion: https://github.com/heroku/heroku-buildpack-nodejs/pull/413
