### ISSUE TITLE
Cache not cleared after changing stacks

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-nodejs#445]
I just switched an app from cedar-14 to heroku-16 and the first build thereafter reused the existing `node_modules` directory:
```
-----> Building dependencies
       Installing node modules (yarn.lock)
       yarn install v0.27.5
       [1/4] Resolving packages...
       success Already up-to-date.
       Done in 1.34s.
```

This seems risky for packages that contain compiled code.

As such, I think it would be good to include `$STACK` in the cache signature here:
https://github.com/heroku/heroku-buildpack-nodejs/blob/da19bdb738fb1ee3ea183ba0a7dd4695843ee383/lib/cache.sh#L3-L5

**Comment by jmorrell** [comment]
It absolutely should be. I'll update next week. 👍
