### ISSUE TITLE
Tests should run against Cedar-14 and Heroku-16

### ISSUE THREAD

**Issue by hunterloftis** [heroku/heroku-buildpack-nodejs#470]
Currently tests run against Cedar-10 (deprecated) and Cedar-14.
The Dockerfile & Makefile should probably use Cedar-14 and Heroku-16 instead.

**Comment by dzuelke** [comment]
They already do :) https://github.com/heroku/heroku-buildpack-nodejs/blob/6d2a9b4719e51e96007c6861f594fd522dfe29af/makefile

**Comment by hunterloftis** [comment]
Scratch that, tests are updated, readme is just out of date (https://github.com/heroku/heroku-buildpack-nodejs#tests)
