### ISSUE TITLE
Use an ENV variable to set NPM version

### ISSUE THREAD

**Issue by evantahler** [heroku/heroku-buildpack-nodejs#477]
The newest version of NPM causes install errors (https://github.com/npm/npm/issues/18520).  If we could set the NPM version via process.env, or even a directive in package.json, that would be helpful.

**Comment by ccurtisj** [comment]
@evantahler I was hitting the same issue on heroku and used `package.json` to specify npm version 5.3.x in the meantime.

https://devcenter.heroku.com/articles/nodejs-support#specifying-an-npm-version

**Comment by jmorrell** [comment]
Closing since this feature already exists, documented at the link above.

**Comment by evantahler** [comment]
Great, thanks!
