### ISSUE TITLE
Default yarn version is outdated (and is an unstable release)

### ISSUE THREAD

**Issue by stof** [heroku/heroku-buildpack-nodejs#478]
The Yarn version used by default is 0.28.4. This version is outdated (latest release is 1.2.1) and was not even considered a stable release by the Yarn team (the last pre-1.0 stable release was 0.27.5).

It would be great if the uptodate version of Yarn could be used by default.

**Comment by jmorrell** [comment]
Thanks for the reminder! I fixed the version of Yarn when `1.0.0` broke on Heroku, but it should be updated.

**Comment by stof** [comment]
@jmorrell do you know when this change will be released ? AFAICT, the deployment done a few hours ago was still using 0.28.4 as default version, so it might be using the latest release rather than the latest master.

**Comment by jmorrell** [comment]
@stof We're currently under a code-freeze until next Friday. So next Friday :)
