### ISSUE TITLE
Yarn cache not cleaned up after recent fixes

### ISSUE THREAD

**Issue by andykant** [heroku/heroku-buildpack-nodejs#494]
I've started tracking `master` until there's another release as suggested, but I noticed an additional issue with the #439/#459 fixes: If Heroku had the previous `.cache` directory cached, those files will continue to exist and throw errors until manually cleaned up. Aside from that, I can verify that #459 fixed my issues.

I worked around this by temporarily pushing `rimraf .cache` as part of my build to clean things up on the Heroku side, which fixed it.

**Comment by jmorrell** [comment]
Hi @andykant! I've released the buildpack changes, so you should be able to point back to the canonical buildpack.

> If Heroku had the previous .cache directory cached

I was trying to puzzle out how this might have worked. Are you saying that you specifically added the cached directory in your `package.json`? [We don't cache these directories by default](https://github.com/heroku/heroku-buildpack-nodejs/blob/master/bin/compile#L12). If not, I'm not sure how it ended up in your Heroku cache.

We also invalidate the cache anytime you use a new version of anything, so bumping your version of node or npm would be an easier solution than adding a special command.

**Comment by andykant** [comment]
This was specifically occurring in Heroku CI (if that happens to cache things a bit differently). I don't have reproduction steps though and I've been able to fix it in my Heroku CI, so I'll close the issue.

Thanks for your time and for the prior fix!
