### ISSUE TITLE
Invalid semver requirement

### ISSUE THREAD

**Issue by mlaythe** [heroku/heroku-buildpack-nodejs#502]
Trying to build Nodejs in an Elixir environment. Keep getting this error `Error: Invalid semantic version "6.11.1"` when I try to deploy to Heroku. I'm worried semver isn't available for some reason. I set my node and npm version in my `package.json` file, but to no avail. Any help is greatly appreciated!

**Comment by hugocattelain** [comment]
Same here : 

Resolving node version 7.7.1...
       Error: Invalid semantic version "7.7.1"
-----> Build failed
 !     Invalid semver requirement
       Node, Yarn, and npm adhere to semver, the semantic versioning convention
       popularized by GitHub.
       http://semver.org/
       However you have specified a version requirement that is not a valid
       semantic version.

**Comment by jmorrell** [comment]
@hugocattelain Can you open a support ticket at https://help.heroku.com and tag @jmorrell? 

This error can occur if the call https://nodebin.herokai.com/v1/node/linux-x64/latest?range=7.7.1 fails with an error, but that version works, so I'd love to dig in and figure out what might be going wrong here.
