### ISSUE TITLE
the buildpack installs yarn prereleases by default

### ISSUE THREAD

**Issue by tikotzky** [heroku/heroku-buildpack-nodejs#512]
currently it installs a prerelease version of yarn if you do not specify an exact yarn version.

It seems like it pulls the yarn version from https://nodebin.herokai.com/v1/yarn/linux-x64/latest.txt

That url is currently returning version 1.4.0 even though 1.4.0 is still a prerelease as seen here https://github.com/yarnpkg/yarn/releases/tag/v1.4.0

**Comment by jmorrell** [comment]
Hmmm... We're pulling down versions using the npm registry API. Ex: `npm info yarn versions`. 

I'll see if we can take prerelease info into account there. Thank you for filing an issue!

**Comment by tikotzky** [comment]
thanks. 
If you run `npm dist-tag ls yarn` (or `yarn tag list yarn`) it'll show that 1.4.0 is published as an `rc` and `latest` is 1.3.4

so 
`npm i yarn --> 1.3.4`
`npm i yarn@rc --> 1.4.0`

**Comment by tikotzky** [comment]
Just an update if you'd like to get a json object with the latest you should be able to switch the api to call `npm info yarn dist-tags`. That currently returns 
```json
{ latest: '1.7.0', rc: '1.8.0' }
```
you you would then be able to pull latest from that list...
