### ISSUE TITLE
Explore using npm ci to install dependencies

### ISSUE THREAD

**Issue by jmorrell** [heroku/heroku-buildpack-nodejs#522]
http://blog.npmjs.org/post/171139955345/v570

**Comment by isaacseymour** [comment]
@jmorrell do you have any thoughts on how this should work? I can imagine two options:

1. if npm version in package.json >= 5.7 and package-lock/npm-shrinkwrap.json is present, use `npm ci`

2. only use `npm ci` if explicitly opted-in (maybe with a `manager` key in `package.json` as suggested in #503 

I would personally go for 2, as I don't think `npm ci` is widely known about yet, so 1 might be a bit of a surprise.

**Comment by jmorrell** [comment]
In theory `npm ci` is what we should use every time if the project has a `package-lock.json`. If we add it to the buildpack it will probably be as a replacement to `npm install` if the version of npm supports it.

I'm not a fan of #2 and adding more config to the build unless there is a very good reason to do so. As much as possible the buildpack should "do the right thing" by default.

One issue that `npm ci` resolves, is that if you update your `package.json` without using `npm install`, your `package-lock.json` will be outdated. When this happens, the next time you run `npm install` it will silently regenerate your `package-lock.json` and you will get a new set of dependencies, and you will not know it.

There are is a good bit of testing and benchmarking to do before I make any sort of change here though, and I'd like `npm ci` to get battle tested elsewhere for a bit first [after the recent issues we experienced with adding `npm prune`](https://github.com/heroku/heroku-buildpack-nodejs/pull/528).

**Comment by SamMorrowDrums** [comment]
Does the fact it removes `node_modules` affect anyone adversely? I doubt it, and it's clearly an anti-pattern - but we wouldn't want people expecting that it would persist.

Caution is a good idea @jmorrell, and a bit of time to let users upgrade and try it out etc. but I think for sure we should move to `npm ci` within a few months. I've already updated a CI server to use it and it's working  well. There was was a duplicate dep with a different version string in the dev dependencies in one project's package.json and `npm ci` does not allow that, while `npm install` accepts it with just a warning. 

:+1: definitely a positive step.

**Comment by ianwremmel** [comment]
Is there a timeline for when this might be done? And is there any way to opt-in immediately? We're running into an issue where a dependency introduced a breaking change in a minor version; since `npm install` doesn't honor the lockfile, we shipped a broken product.

**Comment by jmorrell** [comment]
@ianwremmel no timeline as other projects are currently taking priority. I'll see if I can carve out some time next week though.

If it is an option, [`yarn` already installs with `--frozen-lockfile`](https://github.com/heroku/heroku-buildpack-nodejs/blob/master/lib/dependencies.sh#L94) which will fail the build if `package.json` doesn't match the lockfile.

**Comment by ianwremmel** [comment]
gotcha, thanks! We might go that route, but I think we're going to explore using shrinkwrap instead of the lockfile first.

**Comment by cancan101** [comment]
Any updates on moving over to the ci install? This may speed up the install and would likely turn off the (slow) security audit which should have been run previously and not on Heroku at deploy time (assuming frozen deps).
And by slow I see the following:
```
-----> Building dependencies
       Installing node modules (package.json + package-lock)
       audited 56196 packages in 26.491s
       found 0 vulnerabilities
```

**Comment by patrickmichalina** [comment]
Hoping this gets added soon

**Comment by jskrzypek** [comment]
Can we add the use of `npm ci` behind a flag for now at least? I made a PR (#626) to provide this behavior.

**Comment by glukki** [comment]
> Expect to see movement on this after March 11th.
@jmorrell any updates? how can we help?

**Comment by jmorrell** [comment]
@glukki I'm working on shipping this as an experiment to gather data: https://github.com/heroku/heroku-buildpack-nodejs/pull/676

**Comment by jmorrell** [comment]
Update:

The experiment is currently turned off.

Data from the last week. This is time it takes to install dependencies:

| Measurement | npm install | npm ci |
| --- | --- | -- |
| average | 22.2s | 30.6s |
| median | 8s | 14.1s |
| p90 | 50.9s | 75.1s |
| p95 | 99.5s | 120.1s |
| p99 | 223.9s | 235.4s |

Here `npm install` is faster in every measurement. However, if we only look at builds where the cache was disabled, we get a slightly different story:

| Measurement | npm install | npm ci |
| --- | --- | -- |
| average | 83.9s | 69.3s |
| median | 57.7s | 39.3s |
| p90 | 165s | 157s |
| p95 | 212s | 198s |
| p99 | 383s | 306s |

Here `npm ci` shows a clear advantage, 31% faster by for the median build.

This makes some sense. We are still caching `node_modules` which `npm install` uses when installing, but `npm ci` discards. `npm ci` relies on npm's global cache, which we are not currently caching.

There was also at least one user who experienced downtime as a result of this change because a module that was installed with `npm install` wasn't present in `node_modules` at runtime with `npm ci`. I will be looking into what happened there and why.

There are going to be two follow-up steps here:

- dig into the failure and figure out why it happened and whether it can be worked around
- re-run the experiment but change the caching strategy to save the npm cache directory instead of `node_modules`

**Comment by cancan101** [comment]
Interesting! Is there any way to disable to the security audit in the case of using `npm install`? If so, it might be interesting to see how much faster that makes the install.

**Comment by jmorrell** [comment]
@cancan101 I think that is the `--audit=false` flag, which you *should* be able to set yourself by env var:

```
$ heroku config:set NPM_CONFIG_AUDIT=false -a $APP
```

or with a config in your `.npmrc`:

```
audit = false
```

Overall I think that `npm ci` is likely the better option once were caching the official cache.

**Comment by jmorrell** [comment]
> There are is a good bit of testing and benchmarking to do before I make any sort of change here though, and I'd like npm ci to get battle tested elsewhere for a bit first [after the recent issues we experienced with adding `npm prune`.](https://github.com/heroku/heroku-buildpack-nodejs/pull/528)

Turns out there is a similar, unresolved issue with `npm ci` and `npm prune`: https://npm.community/t/npm-prune-production-after-npm-ci-only-erroneously-uninstalls-regular-dependency/5055

This leaves us with a few options:

- wait for it to be fixed and gate `npm ci` usage on a fixed release like we do for [pruning](https://github.com/heroku/heroku-buildpack-nodejs/blob/master/lib/dependencies.sh#L208)
- contribute a fix for this issue, though there is already [an open PR that may resolve this](https://github.com/zkat/cipm/pull/64)
- fall back to `npm install` for users who would be hit by this edge case through some tricky logic

I'm unsure of what the timeframe on 1 & 2 would be given npm's recent layoffs. I will explore working around this.

Many apologies to the user who experienced downtime as a result of this npm bug

**Comment by usmonster** [comment]
Hello! Any update on this? Maybe it's worth retrying the experiment, at least? Thanks!

**Comment by adsa95** [comment]
Is there any way to manually opt-in (or opt-out) of this experiment? We need to use the same exact build steps on two dynos and we suspect this experiment is the reason why building is failing on one of them with the same commit of code as `npm ci` fails if package.json does not contain a package name, see https://npm.community/t/npm-ci-undefined-failure-when-name-field-missing-from-package-lock-json/9514.

**Comment by danielleadams** [comment]
For anyone that would like to opt in or out of using `npm ci`, you can add a file to the root of your application called `heroku-buildpack-features`. To opt in, the file should contain:
```
use-npm-ci=true
```

To opt out, the file should contain:
```
use-npm-ci=false
```

Here's one of the test fixtures for this: https://github.com/heroku/heroku-buildpack-nodejs/blob/master/test/fixtures/node-10-npm-ci/heroku-buildpack-features

(cc/ @adsa95)

**Comment by danielleadams** [comment]
This has been fully implemented into buildpack.

**Comment by donmb1** [comment]
hey guys. for some reason the opt out does not work for me. I have added the file + buildpack as adviced here but heroku is still using `npm-ci`
Did anything change since 2021?
