### ISSUE TITLE
Building without yarn version specified breaks with failure to fetch yarn 1.5.0

### ISSUE THREAD

**Issue by jrforrest** [heroku/heroku-buildpack-nodejs#523]
Issue cropped up when building with an upstream buildpack (https://github.com/heroku/heroku-buildpack-emberjs) but we're pretty sure it's a failure in this one.

During a build on a project without a Yarn version specified in package.json, the build failed with:

```
Downloading and installing yarn (1.5.0)...
Unable to download yarn: 404
```

Issue was resolved by setting Yarn version to `1.4.1` under `engines` in `package.json`.  Setting `YARN=false` to fall back to npm should also be a viable workaround.

We're thinking that this has something to do with an invalid URL being returned from `https://semver.herokuapp.com/yarn/resolve` during the semver lookup in `install_yarn()`

This did occur in `v98` of this buildpack (since that is what heroku-buildpack-emberjs uses), so this could be cleared up in more recent versions, but since reverting to `1.4.1` fixed the problem we're thinking this may be an issue in more recent versions as well.  Sorry we don't have a straightforward way to check that theory!  Verification of the issue on a more recent version of this buildpack for folks using it directly would be appreciated, apologies if a version bump is all that's needed here.

cc @livfwd

**Comment by jrforrest** [comment]
@mzikherman Mind letting us know what version of the buildpack you guys are on over there?  We'd like to figure out if this is present in versions more recent than `v98`.

**Comment by mzikherman** [comment]
Yup, looks like we are on `v101`.

**Comment by jmorrell** [comment]
> We're thinking that this has something to do with an invalid URL being returned from https://semver.herokuapp.com/yarn/resolve during the semver lookup in install_yarn()

@jrforrest @mzikherman This is likely an issue with pinning the buildpack. We no longer use `semver` in the Node buildpack, and have switched to (nodebin)[https://nodebin.herokai.com/]. This was in release (v109)[https://github.com/heroku/heroku-buildpack-nodejs/blob/master/CHANGELOG.md#v109-2017-07-25].

The ember buildpack was pinned when an upgrade caused it to fail in a difficult to debug way. We'll try again and see if we can update the version pinned there.

If you are pinned to an old version outside of the Ember buildpack then I encourage you to update.
