### ISSUE TITLE
Add Shellcheck linter

### ISSUE THREAD

**Issue by jmorrell** [heroku/heroku-buildpack-nodejs#525]
https://github.com/koalaman/shellcheck

The python buildpack already does this: https://github.com/heroku/heroku-buildpack-python/blob/master/Makefile#L6

**Comment by edmorley** [comment]
Shellcheck would have caught the missing `-r` from `read` (found whilst looking at #571):

```
In lib/output.sh line 12:
  while read LINE;
        ^-- SC2162: read without -r will mangle backslashes.
```

**Comment by jmorrell** [comment]
Done in too many PRs #602 - #610
