### ISSUE TITLE
[QUESTION] how does the buildpack strip out devDeps?

### ISSUE THREAD

**Issue by justinhelmer** [heroku/heroku-buildpack-nodejs#533]
if you are installing all deps regardless of prod vs no (i.e. deps and devdeps), how can you possibly prune devDeps? with npm 3+, since modules are all flattened, how does pruning guarantee only modules that are non-prod are pruned?

For example, you might have a `devDependency` of `webpack` - but you also might have a `dependency` that (at some point down the chain) requires `webpack` as an actual dependency.

How does the prune logic only remove unneeded modules, without deleting everything and re-installing with the right `NODE_ENV` (or `-p` flag)?

...

This is for macys by the way. Hunter we actually met when macys came over to heroku at the beginning of the partnership but that was many moons ago.

**Comment by jmorrell** [comment]
Hi @justinhelmer! @hunterloftis now manages the languages team, and I took his position as the Node owner.

The short answer to your question is `npm prune`: https://docs.npmjs.com/cli/prune

> If the --production flag is specified or the NODE_ENV environment variable is set to production, this command will remove the packages specified in your devDependencies. Setting --no-production will negate NODE_ENV being set to production.

> How does the prune logic only remove unneeded modules, without deleting everything and re-installing with the right NODE_ENV (or -p flag)?

Both npm and yarn will recalculate the entire dependency tree and remove those modules from disk that are no longer present in the new `dependencies`-only tree.

Does this answer your question?

**Comment by justinhelmer** [comment]
Hey @jmorrell - thanks for the thoughtful reply.

This absolutely makes sense. I did not realize it recalculates the whole tree, which is the only way it could work.

Thanks a lot; I will close this issue unless a more discrete description of the macys problem comes up.

Cheers.

**Comment by jmorrell** [comment]
@justinhelmer what problem is macy's having? Feel free to open a support ticket and request it be escalated to the Node team
