### ISSUE TITLE
Warn users about vulnerabilities with npm audit

### ISSUE THREAD

**Issue by SamMorrowDrums** [heroku/heroku-buildpack-nodejs#538]
`npm audit` is coming very soon with NPM 6, and while I'm loath to suggest we needlessly add build steps that don't do building, it could help to reduce the amount of insecure 3rd party code being deployed. I would only propose it as a warning though.

Maybe the buildpack is not the place to do this, but warning users pushing code with known vulnerabilities could be a helpful feature.

https://medium.com/npm-inc/announcing-npm-6-5d0b1799a905

**Comment by cancan101** [comment]
I think audit is run by default on `npm install` (https://docs.npmjs.com/auditing-package-dependencies-for-security-vulnerabilities).
https://github.com/heroku/heroku-buildpack-nodejs/blob/f6d55d632a84bc1a83d20bb15ce4d186846cff6d/lib/dependencies.sh#L157

**Comment by SamMorrowDrums** [comment]
Might be worth checking of it's the case with NPM CI as that may differ and is likely the future of this package I'd assume.

I've closed anyway as its covered as is for now.
