### ISSUE TITLE
Pruning dev dependencies fails when the npm registry has issues

### ISSUE THREAD

**Issue by stof** [heroku/heroku-buildpack-nodejs#543]
As far as I understand, pruning dev dependencies should be only about removing packages, and so should work offline. but this is not the case. With the npm registry down (as is the case right now), I get build failures while pruning dev dependencies (the initial install worked fine thanks to the cache)

**Comment by jmorrell** [comment]
Thanks for bringing this failure mode to my attention, but I'm not certain this is actionable. I agree that it is odd that `npm prune` would fail without being able to talk to the registry.

**Comment by stof** [comment]
Note that my project is using yarn. So it may be a yarn issue

**Comment by jmorrell** [comment]
Closing as Not Actionable. If the npm registry is down that's a valid point of failure for deploying Node apps.
