### ISSUE TITLE
Promoting Node JS app via Heroku Pipelines copies environment variables from staging

### ISSUE THREAD

**Issue by nholden** [heroku/heroku-buildpack-nodejs#545]
I have an application that's using the Node JS buildpack on Heroku, and I saw that I should be able to [use `process.env` to access environment variables](https://devcenter.heroku.com/articles/getting-started-with-nodejs#define-config-vars).

The application uses Heroku Pipelines, and when I promote my application from staging to production, `process.env` in production still references the staging environment variables. When I push directly to production using `git push`, `process.env` references the production environment variables correctly.

I'm not sure what the best way would be to provide a reproducible test case for this one would be. If you have any ideas, or if there's any more information I can provide, please let me know. Thank you!

**Comment by nholden** [comment]
Ah, shoot. I think the places where I'm using `process.env` are being compiled when I push to staging, so I have a [stateful build](https://devcenter.heroku.com/articles/pipelines#release-phase-during-a-promotion). I'll need to rethink this.

**Comment by nholden** [comment]
Thanks, @jmorrell! Yes, that's exactly what I'm doing. Webpack bundles the JS in the browser as part of the build. I'll give your suggestions a shot.

**Comment by edmorley** [comment]
You might be able to borrow some ideas from:
https://github.com/mars/create-react-app-buildpack#runtime-configuration
https://github.com/mars/heroku-js-runtime-env

**Comment by nholden** [comment]
Thank you, @edmorley! I'll take a look.

**Comment by nholden** [comment]
Thanks again for your suggestions! The documentation around `create-react-app-buildpack` was especially useful in helping me understand the difference between "compile-time" and "runtime" environment variables.

In case it's useful for anyone else who comes along this issue, I ended up handling this configuration outside of Webpack. In my server-rendered HTML, I added a new script tag before my Webpack tag with a global `window.env` object that included just the environment variables that were safe to expose to the browser. With that in place, I was able to promote my application via Heroku pipelines without copying over environment variables.

[Here's what that looked like](https://github.com/nholden/crawl_vote/commit/cd1b89dff4812da1270d6a5d54b594aecb1a5ca7).

**Comment by gsunsnackv** [comment]
I just ran into this issue. I wish heroku has the option to rebuild when promote. We have ejected our react app so the solutions here are not working. Except build at run time, which make the start so slow

**Comment by malko42** [comment]
You can have a loot at that article https://devcenter.heroku.com/articles/release-phase
You can define a `release` task in your `Procfile` which will be run on release (e.g. build your application)

**Comment by jmorrell** [comment]
@malko42 please note https://devcenter.heroku.com/articles/release-phase#design-considerations

> Release phase is not suitable for tasks that require filesystem persistence, as filesystem changes during release phase will not be deployed to your app’s dyno formation (the dyno filesystem is ephemeral). Asset compilation should happen during builds. Release phase can be used to upload the compiled assets to a CDN.

Release phase should not be used for asset compilation since the assets cannot be persisted to disk

**Comment by malko42** [comment]
@jmorrell Oh! Thank you for catching that.
I guess I will just delete my message and ask for a 'build on promote' option :)
