### ISSUE TITLE
Npm error when trying to deploy with local modules 

### ISSUE THREAD

**Issue by shakesBeardZ** [heroku/heroku-buildpack-nodejs#573]
I'm having this problem while trying to deploy my app to heroku (everything works fine locally and in my server )

![image](https://user-images.githubusercontent.com/15571628/46256965-80449080-c4b2-11e8-8069-25020eefbd66.png)

I use local files to package and install a few node modules 

![image](https://user-images.githubusercontent.com/15571628/46256981-a407d680-c4b2-11e8-8b1a-843dc6e3faa5.png)

**Comment by jmorrell** [comment]
Hi! Can you open a support ticket at help.heroku.com? It's much easier to debug app-specific issues there
