### ISSUE TITLE
nvmrc support

### ISSUE THREAD

**Issue by Kjwon15** [heroku/heroku-buildpack-nodejs#579]
Currently, this buildpack assumes node version by parsing package.json, engines.npm, engines.yarn.
nvmrc also can specifying node versions to.

**Comment by jmorrell** [comment]
This a great suggestion, but I'm against allowing more than one way of specifying a specific configuration if we can help it

**Comment by nedtwigg** [comment]
> I'm against allowing more than one way of specifying a specific configuration if we can help it

Me too!  But our code runs in environments besides Heroku servers (namely dev machines).  So unless the buildpack supports .nvmrc, then we are forced to have multiple versions specified in different places, and it's on us to keep them in sync.

**Comment by bencooper222** [comment]
+1 to reconsidering this. `.nvmrc` is even more standard now.
