### ISSUE TITLE
Intent to ship: Run 'build' script by default

### ISSUE THREAD

**Issue by jmorrell** [heroku/heroku-buildpack-nodejs#583]
Previous discussion: https://github.com/heroku/heroku-buildpack-nodejs/issues/479

While we offer support for running build scripts using `heroku-prebuild` and `heroku-postbuild` hooks, the community has coalesced around using `build` for build scripts. Many boilerplates don't work out of the box on Heroku due to not running build by default.

Making the buildpack automatically run the `build` script is relatively straight-forward, however it's difficult to ship because of the following:
![](https://s3.amazonaws.com/snapshots.librato.com/chart/gsf9zh5r-270692.png)

~20% of Node.js deploys currently define a `build` script, but do not define a `postinstall` or `heroku-postbuild` script, which means that starting to run this script will "light up" a bunch of code not currently being used in deploys. This makes it a breaking change.

Given the widespread use of the `build` script in the frontend community, we feel that a breaking change here is justified, but we are going to be careful about how we roll it out.

Steps:
- [x] Make the change opt-in for the first N days
- [x] Make opting-in to the change only require 1 command
- [x] Add warnings to the builds of users who may be affected by the change
- [x] Email users who will be affected by this change

Examples of projects using the `build` script by default:

create-react-app: https://github.com/facebook/create-react-app/tree/next/packages/react-scripts/template#npm-run-build
ng-cli: https://github.com/angular/angular-cli/blob/master/package.json#L13
next.js: https://github.com/zeit/next.js/#setup
gatsby.js: https://www.gatsbyjs.org/docs/deploy-gatsby/#heroku
vue-cli: https://cli.vuejs.org/guide/cli-service.html

**Comment by edmorley** [comment]
> ~20% of Node.js deploys currently define a `build` script, but do not define a `postinstall` or `heroku-postbuild` script

Out of curiosity, do you know of why this might be?

I can think of:
1. there are additional automatically run `package.json` scripts that people are using that are not included in the [currently recorded metrics](https://github.com/heroku/heroku-buildpack-nodejs/blob/998beb13be16f0d96293900fc16a7b6bbb13e4b1/lib/dependencies.sh#L49-L51) (eg `prepare`, `install`, [others](https://docs.npmjs.com/misc/scripts))
2. they commit their built assets to the repository so don't need to run them at Heroku compile time
3. they run `build` via some other non-`scripts` means (eg via a later buildpack's hooks)
4. they use `build` for something unrelated to building their app for deployment, or else it's just a leftover from a previous implementation and so deadcode

As as a single data point, for one of our apps we fall under (3) in that we run `yarn build` via the Python buildpack's `bin/post_compile` script - the reason for this being that we have a number of other post compile tasks that require Python so were keeping all custom steps together (plus `post_compile` supports code comments). (However independent of this proposed buildpack change we've just switched to using `heroku-postbuild` instead, so won't be affected by this change.)

**Comment by jmorrell** [comment]
After talking to some people, going to push this off until after Thanksgiving / Black Friday since the timing is a little tight

**Comment by jmorrell** [comment]
Changelog published: https://devcenter.heroku.com/changelog-items/1557

**Comment by edmorley** [comment]
Hi!

We received the notification email for our enterprise team.

One of the apps within that email was:
https://dashboard.heroku.com/apps/ensemble-transposer

However that apps uses the `container` stack, so isn't using the `heroku-buildpack-nodejs` buildpack set for the app.

Another app listed was:
https://dashboard.heroku.com/apps/taskcluster-task-analysis

That app is already running `build` via `postinstall`:

```js
  "scripts": {
    "build": "neutrino build",
    "test": "neutrino test",
    "postinstall": "yarn build",
    "start": "node . server",
    "startEventListener": "node . eventListener"
  },
```

And it seems like this case should be handled here?
https://github.com/heroku/heroku-buildpack-nodejs/blob/bc532006e1b861165f1b1a38e57eb8d4fb9bad2b/lib/dependencies.sh#L130-L134

...unless perhaps apps falling into this category were emailed regardless to avoid confusion? :-)

**Comment by jmorrell** [comment]
Hi @edmorley!

> However that apps uses the `container` stack, so isn't using the `heroku-buildpack-nodejs` buildpack set for the app.

Ah, thanks for letting me know! I'll use that to refine query for the apps we send reminders out about in 2 weeks 👍 

> That app is already running `build` via `postinstall`:

That's not an error. There is no special handling around `postinstall` in the buildpack. The code you quoted was just added to get numbers around how many people fell into that bucket. If that app is not updated it will execute the build twice when this rolls out next month.

Options for updating it:

- opt-in, delete `postinstall`, and use `build` directly. This is what `npx @heroku/update-node-build-script` will do for you
- Keep `postinstall` if that workflow is preferable and add an empty `heroku-postbuild`

**Comment by jmorrell** [comment]
This is done! 🎊
