### ISSUE TITLE
yarn test is not using NODE_ENV test but runs in production context 

### ISSUE THREAD

**Issue by gkatsanos** [heroku/heroku-buildpack-nodejs#598]
It seems heroku is ignoring of over-writing a NODE_ENV variable from my package.json .
```
    "test": "NODE_ENV=test nyc --reporter=html --reporter=text mocha --timeout 20000 --recursive src/tests",
```

now they are run with production rights... :/

**Comment by jmorrell** [comment]
@gkatsanos I don't really understand how the buildpack could override an ENV var you've preprended to the test command here... 

I saw https://github.com/gkatsanos/boilerplate-server/commit/e9dd72d4c80c6ac00b8bbc5f9230ae65a79ffd01. Were you using an old version of the buildpack? Feel free to open a support ticket at help.heroku.com because I'm not sure what is happening here

**Comment by jmorrell** [comment]
We set `NODE_ENV` to `test` when building for CI: https://github.com/heroku/heroku-buildpack-nodejs/blob/master/bin/test-compile#L8

**Comment by gkatsanos** [comment]
I think I fixed it by hard-specifying the buildpack version : 
heroku buildpacks:set https://github.com/heroku/heroku-buildpack-nodejs#v134 -a boilerplate-server
(originally I had started this more than a year ago so I think the bug was not fixed then?)

I wonder why just setting it without version didn't default to the latest one..

**Comment by jmorrell** [comment]
@gkatsanos Unless you specifically pin to a specific git tag, you should always get the latest buildpack version. It's aliased as `heroku/nodejs`:

```
$ heroku buildpacks:set heroku/nodejs
```

Looking at the builds for `boilerplate-server` I can confirm that you were using the latest published version, and none of the relevant code has changed in quite some time...

Even in the old version, the buildpack should not be able to overwrite a `NODE_ENV` env var set explicitly in the `test` command like you have above unless I'm misunderstanding something. You can test this by using a different test command:

```
"test": "NODE_ENV=something-specific node -e "console.log(process.env.NODE_ENV)"",
```

The above should always output `something-specific` no matter what the buildpack sets for `NODE_ENV`.

If your current set up is working for you, that's great! If you want to dig in to what might have happened here then please open a support ticket.
