### ISSUE TITLE
An unexpected error occurred: "Script must exist"

### ISSUE THREAD

**Issue by ideallical** [heroku/heroku-buildpack-nodejs#622]
In my package.json I had:

`scripts: {
    heroku-postbuild: ""
}`

Deploying always worked until recently.
I think it has to do with this recent commit: https://github.com/heroku/heroku-buildpack-nodejs/commit/57b6c87bffee00b70f9765a5b14180dd698ec6b6

Not sure if this is intended behaviour, but it took me awhile to find out it was due to an empty string in the heroku-postbuild property. Perhaps "Script in heroku hook must exist" would be a more helpful error message.

**Comment by jmorrell** [comment]
Hi @ideallical! 

Can I ask why you have an empty `heroku-postbuild` script?

This does sound like a bug. I'll investigate and get a fix out this week.

**Comment by ideallical** [comment]
I don't know why it was blank, it has been like this since the first commit in our project.

Thanks!

**Comment by jmorrell** [comment]
This is due to yarn throwing an error when the script is empty. We can work around this.
