### ISSUE TITLE
Changelog is missing entries

### ISSUE THREAD

**Issue by OliverJAsh** [heroku/heroku-buildpack-nodejs#632]
I am trying to understand a behaviour difference after upgrading, however the changelog is missing a few of the most recent versions.

Would it be possible to get the changelog updated?

**Comment by jmorrell** [comment]
Closing based off discussion in https://github.com/heroku/heroku-buildpack-nodejs/pull/633

**Comment by OliverJAsh** [comment]
AFAICS the change log is still missing the most recent few versions. Can we re open?

**Comment by jmorrell** [comment]
Oh yes, I'll get that fixed
