### ISSUE TITLE
MERN Deployment is failing when deployed at Heroku

### ISSUE THREAD

**Issue by waditya** [heroku/heroku-buildpack-nodejs#641]
Hello everyone,

I am new to React development. I have created a React application. It is running perfectly well on localhost. When I try to deploy to Heroku, I am getting error. I am trying to troubleshoot for last 13 hours but no luck. Any help or guidance is appreciated.

The Repository is as below - 
https://github.com/waditya/TripWithUs2

E:\03 Spring 2019\ISTM 631 601 Information System Design and Development Project\TripWithUs2>git push heroku master

### Counting objects: 84, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (78/78), done.
Writing objects: 100% (84/84), 7.97 MiB | 1.32 MiB/s, done.
Total 84 (delta 13), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Node.js app detected
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:        NODE_VERBOSE=false
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  10.13.0
remote:        engines.npm (package.json):   6.7.0
remote:
remote:        Resolving node version 10.13.0...
remote:        Downloading and installing node 10.13.0...
remote:        Bootstrapping npm 6.7.0 (replacing 6.4.1)...
remote:        npm 6.7.0 installed
remote:
remote: -----> Installing dependencies
remote:        Installing node modules (package.json)
remote:
remote:        > jss@9.8.7 postinstall /tmp/build_a6cc0f9d48bb89d82f2a8b93e6b402fc/node_modules/jss
remote:        > node -e "console.log('\u001b[35m\u001b[1mLove JSS? You can now support us on open collective:\u001b[22m\u001b[39m\n > \u001b[34mhttps://opencollective.com/jss/donate\u001b[0m')"
remote:
remote:        Love JSS? You can now support us on open collective:
remote:         > https://opencollective.com/jss/donate
remote:        added 731 packages from 437 contributors and audited 8706 packages in 22.823s
remote:        found 0 vulnerabilities
remote:
remote:
remote: -----> Build
remote:        Detected both "build" and "heroku-postbuild" scripts
remote:        Running heroku-postbuild
remote:
remote:        > mern_concord@1.1.3 heroku-postbuild /tmp/build_a6cc0f9d48bb89d82f2a8b93e6b402fc
remote:        > cd client && npm --production=false && npm run build
remote:
remote:
remote:        Usage: npm <command>
remote:
remote:        where <command> is one of:
remote:            access, adduser, audit, bin, bugs, c, cache, ci, cit,
remote:            clean-install, clean-install-test, completion, config,
remote:            create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
remote:            edit, explore, get, help, help-search, hook, i, init,
remote:            install, install-ci-test, install-test, it, link, list, ln,
remote:            login, logout, ls, org, outdated, owner, pack, ping, prefix,
remote:            profile, prune, publish, rb, rebuild, repo, restart, root,
remote:            run, run-script, s, se, search, set, shrinkwrap, star,
remote:            stars, start, stop, t, team, test, token, tst, un,
remote:            uninstall, unpublish, unstar, up, update, v, version, view,
remote:            whoami
remote:
remote:        npm <command> -h  quick help on <command>
remote:        npm -l            display full usage info
remote:        npm help <term>   search for help on <term>
remote:        npm help npm      involved overview
remote:
remote:        Specify configs in the ini-formatted file:
remote:            /app/.npmrc
remote:        or on the command line via: npm <command> --key value
remote:        Config info can be viewed via: npm help config
remote:
**remote:        npm@6.7.0 /tmp/build_a6cc0f9d48bb89d82f2a8b93e6b402fc/.heroku/node/lib/node_modules/npm
remote: npm ERR! code ELIFECYCLE
remote: npm ERR! errno 1
remote: npm ERR! mern_concord@1.1.3 heroku-postbuild: `cd client && npm --production=false && npm run build`
remote: npm ERR! Exit status 1
remote: npm ERR!
remote: npm ERR! Failed at the mern_concord@1.1.3 heroku-postbuild script.
remote: npm ERR! This is probably not a problem with npm. There is likely additional logging** output above.
remote:
remote: npm ERR! A complete log of this run can be found in:
remote: npm ERR!     /tmp/npmcache.0AD39/_logs/2019-03-26T00_59_31_784Z-debug.log
remote:
remote: -----> Change to Node.js build process
remote:        Heroku has begun executing the "build" script defined in package.json
remote:        during Node.js builds.
remote:
remote:        Read more: https://devcenter.heroku.com/changelog-items/1573
remote:
remote:
remote: -----> Build failed
remote:
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:
remote:        If you're stuck, please submit a ticket so we can help:
remote:        https://help.heroku.com/
remote:
remote:        Love,
remote:        Heroku
remote:
remote:  !     Push rejected, failed to compile Node.js app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to tripwithus2.
remote:
To https://git.heroku.com/tripwithus2.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/tripwithus2.git'

E:\03 Spring 2019\ISTM 631 601 Information System Design and Development Project\TripWithUs2>

**Comment by jmorrell** [comment]
Hi @waditya, I'm afraid this issues list is meant for discussing issues with the Node buildpack, not for providing one-off support for application developers. Please open a ticket at https://help.heroku.com/
