### ISSUE TITLE
Install devDependencies in subdirectories

### ISSUE THREAD

**Issue by ridhwaans** [heroku/heroku-buildpack-nodejs#656]
app is structured like
```
package.json
client/
-package.json
-webpack.config.js
```

`webpack` + exclusive dependencies are in `package.json` of client subfolder 
at the top level, `package.json` has
```
"scripts": {
    "client": "cd client && yarn build",
    "start": "node server.js",
    "heroku-postbuild": "yarn client"
  }
```
Heroku deploy returns `failed: webpack not found`. How do I tell the nodejs buildpack to install from two package.jsons? considered using `NPM_CONFIG_PRODUCTION=false` and `heroku-prebuild` to cd to install

**Comment by ridhwaans** [comment]
resolved after adding `"postinstall": "cd client && npm install",`

**Comment by nisan-cb** [comment]
i try it and it works,
but the webpack (and all other packages that in use in webpack process like ts-load) should to be in dev-dependencies.
and heroku not install the dev-dependencies from sub folders.
so, my question is how to install also the dev-dependencies from sub folder in heroku deployment process and remove the after build process like the behavior in the root package.json ?
