### ISSUE TITLE
Is there a way to remove (or disable) PATH entries like node, npm, and node_modules/.bin?

### ISSUE THREAD

**Issue by frederikhors** [heroku/heroku-buildpack-nodejs#702]
Is there a way to remove (or disable) `PATH` entries like `node`, `npm`, and `node_modules/.bin`?

For a security POV I wanna use this buildpack just for building my assets in a `build` directory.

I don't need anything after the build.

**Is there a way to cleanup the `nodejs` "layer" from the slug?**

**Comment by danielleadams** [comment]
@frederikhors Are you using multiple buildpacks? You can remove Node via `rm -rf` from a subsequent buildpack.

**Comment by danielleadams** [comment]
@frederikhors going to close this due to inactivity. If there's an issue with the buildpack, please feel free to reopen.
