### ISSUE TITLE
Caching Error

### ISSUE THREAD

**Issue by Jytesh** [heroku/heroku-buildpack-nodejs#738]
ll try to explain, first as soon as the message is received a skin js object is built and sent to this functionretrieveskin), an embed(think a loading animation) is sent and that message is stored.Then canvas makes an image for me(which takes some time mind it) using the skin object(different image for each command) so once that image is build, the loading embed is deleted and the new one is sent, if the image fails to build the Error Time Out function(after 10 seconds) is called, and the loading embed becomes an error embed
https://hastebin.com/pimovaxila.js - The embed gets deleted after my image is sent, if i use node in my terminal, but it won't get deleted if i use heroku(sometimes)

**Comment by danielleadams** [comment]
@Jytesh This looks like an issue you're having with Heroku platform, and less with the Node buildpack. Have you tried opening a ticket for this issue? It'll help us triage the issue appropriately. You can do that here: https://help.heroku.com/

**Comment by Jytesh** [comment]
> @Jytesh This looks like an issue you're having with Heroku platform, and less with the Node buildpack. Have you tried opening a ticket for this issue? It'll help us triage the issue appropriately. You can do that here: https://help.heroku.com/

I'm sorry but its a free application so I can't open a ticket.

**Comment by danielleadams** [comment]
@Jytesh were you able to find a solution for this issue?

**Comment by Jytesh** [comment]
Sadly no, I had to rewrite my entire code and give it a better error handling structure.
