### ISSUE TITLE
Buildpack failing instantly, suddenly?

### ISSUE THREAD

**Issue by ckcollab** [heroku/heroku-buildpack-nodejs#749]
```
-----> Node.js app detected
/app/tmp/buildpacks/.../bin/compile: line 26: 
/app/tmp/buildpacks/.../etc/vendor/stdlib_v7.sh: No such file or directory
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

Getting this instantly on builds now, across multiple apps (don't think error is on my end)

**Comment by AugustMiller** [comment]
Just came to report the same thing—odd, granted the file still exists in the build pack, at this location!

We're blocked on deployments until this is resolved, although… there's an alternative syntax for specifying a version with a hash: https://devcenter.heroku.com/articles/buildpacks#buildpack-references

I'll post another comment if I can get this working. :v:

**Comment by billyburgoa** [comment]
I am getting the same messages.
```
-----> Node.js app detected

/app/tmp/buildpacks/a104ebb80184ba556a3457859a381585c1c182694d8086bfcdabe39f3fe5857835812b209be5647b385deaddf7afa081b0f0c5d9d1683b767fb8abc0c3b79cc0/bin/compile: line 26: /app/tmp/buildpacks/a104ebb80184ba556a3457859a381585c1c182694d8086bfcdabe39f3fe5857835812b209be5647b385deaddf7afa081b0f0c5d9d1683b767fb8abc0c3b79cc0/etc/vendor/stdlib_v7.sh: No such file or directory

 !     Push rejected, failed to compile Node.js app.

 !     Push failed
```

**Comment by ozeas** [comment]
Mesma coisa.
```

-----> Node.js app detected
/app/tmp/buildpacks/a104ebb80184ba556a3457859a381585c1c182694d8086bfcdabe39f3fe5857835812b209be5647b385deaddf7afa081b0f0c5d9d1683b767fb8abc0c3b79cc0/bin/compile: line 26: /app/tmp/buildpacks/a104ebb80184ba556a3457859a381585c1c182694d8086bfcdabe39f3fe5857835812b209be5647b385deaddf7afa081b0f0c5d9d1683b767fb8abc0c3b79cc0/etc/vendor/stdlib_v7.sh: No such file or directory
```

**Comment by AugustMiller** [comment]
## Temporary Fix to roll back to `v167` release:

```
$ heroku buildpacks:set 'https://github.com/heroku/heroku-buildpack-nodejs#v167' --app your-app-name
```

**Comment by billyburgoa** [comment]
> **Temporary Fix to roll back to `v167` release:**
> 
> ```
> $ heroku buildpacks:set 'https://github.com/heroku/heroku-buildpack-nodejs#v167' --app your-app-name
> ```
> 
> (I am not an author, and not sure if this is the recommended route, but it's gotten our app back online!)

I don't know which version of my app is running in heroku. The mine is still running, though.

**Comment by danielleadams** [comment]
I rolled back the buildpack, so this should be working again. The buildpack is using v167 by default now.

**Comment by ozeas** [comment]
> **Temporary Fix to roll back to `v167` release:**
> 
> ```
> $ heroku buildpacks:set 'https://github.com/heroku/heroku-buildpack-nodejs#v167' --app your-app-name
> ```
> 
> (I am not an author, and not sure if this is the recommended route, but it's gotten our app back online!)

it worked for me too.

**Comment by billyburgoa** [comment]
Things seem to be working fine again. I just deployed the branch and it got compiled without any issues.

**Comment by danielleadams** [comment]
Going to close this since I rolled back. Please see my previous comment: https://github.com/heroku/heroku-buildpack-nodejs/issues/749#issuecomment-606182794

**Comment by AugustMiller** [comment]
Thanks for the quick response! 💓

**Comment by getbizzey** [comment]
Thanks for the quick response!

Stay safe!
