### ISSUE TITLE
Unknown error installing "12.16.3" of node

### ISSUE THREAD

**Issue by sayem314** [heroku/heroku-buildpack-nodejs#772]
```
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=false
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  12.16.3
       engines.npm (package.json):   unspecified (use default)
       engines.yarn (package.json):  unspecified (use default)
       
       Resolving node version 12.16.3...
       Error: Unknown error installing "12.16.3" of node
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

**Comment by danielleadams** [comment]
@sayem314 Did you have successful builds after this? Or do you have a build ID? I've linked how to get it here: https://github.com/heroku/heroku-buildpack-nodejs/issues/760#issuecomment-618011332

**Comment by sayem314** [comment]
No success so far. Even without other versions. Here is a list of all failed builds.

`df73f1bc-0f9b-430a-94b5-cd23137f6032`
`29d43157-4ac8-4fe3-bd92-e63c910c7d05`
`623c2cd2-e048-4c69-ba06-8693c7b18d9b`
`027430fa-dd51-439e-9e95-8502e502adff`
`923554f5-979b-4fec-994f-455489d87971`

**Comment by danielleadams** [comment]
@sayem314 Took a peak, and I think it's this issue: https://github.com/heroku/heroku-buildpack-nodejs#proxy-issues

Does this need to be set for the build?

**Comment by sayem314** [comment]
That worked. Thanks @danielleadams
