### ISSUE TITLE
Error deploying MERN application to Heroku (Front-end deployed successfully, but the back-end didn't)

### ISSUE THREAD

**Issue by ikhromwicaksono-git** [heroku/heroku-buildpack-nodejs#793]
I've been struggling with this section for about 10+ hours. I tried doing my research on it and discovering the problem. I tried a few solutions but can't seem to get it to work for me. I have everything set up exactly the way BradTraversy has it, but for some reason, mine isn't deploying. Local development works perfectly fine with both the front and the back end of things.

The problem is that when I deploy to production onto Heroku. It shows the back-end, but then the front end decides not to work. 

this my server.js
![Screen Shot 2020-06-23 at 21 37 47](https://user-images.githubusercontent.com/57649629/85417836-48408380-b59a-11ea-8995-18baca29cc7b.png)

my package.json
![Screen Shot 2020-06-23 at 21 42 05](https://user-images.githubusercontent.com/57649629/85418105-96558700-b59a-11ea-9c80-19ce2f22b396.png)

**Comment by danielleadams** [comment]
@ikhromwicaksono-git can you link to the article you are referring to? Is there an error you are seeing? A build ID? I can't really do much with these screenshots. Thanks!

**Comment by danielleadams** [comment]
@ikhromwicaksono-git were you able to figure this out?

**Comment by danielleadams** [comment]
Going to close due to inactivity.
