### ISSUE TITLE
Option to keep existing node_modules on build

### ISSUE THREAD

**Issue by llhupp** [heroku/heroku-buildpack-nodejs#797]
Hey there! I've got a small feature request. We have a pretty extensive build pipeline that runs before our code is sent to heroku. Since that pipeline installs and caches all node_modules itself, I thought it would save some time to zip those into the tar that is deployed to heroku. However, it seems [this line deletes node_modules if they are present.](https://github.com/heroku/heroku-buildpack-nodejs/blob/master/bin/compile#L206) Could there be a flag added that allows us to skip that?

**Comment by danielleadams** [comment]
Hi @llhupp! I am in the process of supporting Yarn 2, which does exactly this - it will zip the dependencies so that the build doesn't have to download them. Is this the use case you are solving for (and using node modules instead with some sort of link) or are the modules being zipped a different way? Thanks for your patience here.

**Comment by danielleadams** [comment]
@llhupp would you be interested in testing with the feature branch that we have for Yarn 2?

**Comment by llhupp** [comment]
I appreciate the quick communication and feedback! Unfortunately, I don't know if I'd have time to test out yarn 2 since I don't have any projects utilizing it currently. I'm fine with shelving this and revisiting if it is still an issue after the yarn 2 work is done. In the meantime, the slower build times aren't that pressing.

**Comment by danielleadams** [comment]
@llhupp while this issue hasn't been resolved, I believe your specific use case is solved with Yarn 2 support, so let me know if we can close this.

**Comment by llhupp** [comment]
I'm not familiar with all of the new features of yarn 2, but I don't think it will address this specific issue I'm having with the buildpack. I am sending a zipped folder that contains my entire application directory (with installed node_modules and compiled source) to heroku. All I really need the buildpack to do is run my start command (`yarn start` in my case). However, it deletes and reinstalls all of the node_modules I sent, and I would like to prevent that.

**Comment by danielleadams** [comment]
Oh! Okay. I was misunderstanding the use case. We can support this. I'll make clarifying comments in your pull request.

**Comment by danielleadams** [comment]
Fixed with https://github.com/heroku/heroku-buildpack-nodejs/pull/798
