### ISSUE TITLE
fs.readFile not working when deployed on heroku

### ISSUE THREAD

**Issue by Karan-Gandhi** [heroku/heroku-buildpack-nodejs#801]
Hello, I recently ran into a problem where I had to read `.jpg` files using `fs.readfile()` and encode in `base64` format. I used the following line of code.
```
fs.readFile("./images/" + this.link, "base64", (err, data) => {
    if (err) console.log(err);
    else {
        this.base64 = "data:image/jpg;base64, " + data;
        console.log("[FILESTREAM] " + this.link + " loaded");
    }
});
```
This works fine when I run it on the local server, but when I deploy my code to `heroku` then some Images are loaded but the others are not being loaded and I am getting a error when I run `heroku log --tail` in my terminal
```
[Error: ENOENT: no such file or directory, open './products/images/Aloevera with Walnut & Apricot Scrub Face Wash.jpg'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './products/images/Aloevera with Walnut & Apricot Scrub Face Wash.jpg'
}
[Error: ENOENT: no such file or directory, open './products/images/Amla Bhingraj Shampoo.jpg'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './products/images/Amla Bhingraj Shampoo.jpg'
}
[FILESTREAM] Tea Tree Face Wash.jpg loaded
[FILESTREAM] Aloevera Gel.jpg loaded
[FILESTREAM] Almond Saffron Moisturizer.jpg loaded
[FILESTREAM] Jasmine Mogra Body Wash.jpg loaded
```
At first I thought that some of the images might not be uploaded due to its file size but when I run `heroku run bash` and navigate to that directory then I find that all the images are uploaded properly.
```
~/products/images $ ls
'Almond Saffron Moisturizer.jpg'  'Aloevera with Walnut & Apricot Scrub Face Wash.JPG'  'Charcoal Soap.JPG'            'Jasmine Mogra Body Wash.jpg'
'Aloevera Gel.jpg'                'Amla Bhingraj Shampoo.JPG'                           'Cucumber Mint Face Mist.JPG'  'Tea Tree Face Wash.JPG'
```
Is there any way to fix this? Thank you!

**Comment by danielleadams** [comment]
Hi @Karan-Gandhi - on first glance, does it have to do with the file extension not matching? `.JPG` vs. `.jpg`? Without seeing where `this.link` comes from, it's hard to tell. 

My other questions would be:
- Are the errors are random or always at the beginning? Could it be that the haven't been fully extracted from the slug when the script runs?
- Is there zero-width-whitespace that is causing the file names to be mismatched?
- Have you tried escaping the white space?

Hope these are helpful. Happy to help you debug this.

**Comment by Karan-Gandhi** [comment]
Hello, I tried changing the extension name from `.JPG` to `.jpg` of the files which are not read but it did not yield any results. I tried logging the link (`this.link`) and it was also not empty. The errors are there from the beginning and it has been the same files that are not read. As mentioned above it works perfectly fine on the local server. Other images that have whitespace are read perfectly fine.

However, I recently tried moving all of the images to the client side and found out that the problem is not only pertaining to `fs.readFile`. I tried to make a image tag and setting the `src` attribute to the image link but it gave the same result.

**Comment by danielleadams** [comment]
@Karan-Gandhi it sounds like this may be an issue with the file not being added to the slug properly. Were you able to figure out the issue?

**Comment by Karan-Gandhi** [comment]
No I have not yet been able to figure out the issue

**Comment by danielleadams** [comment]
Have you tried opening a support ticket? We would be able to gain better insight.

**Comment by danielleadams** [comment]
@Karan-Gandhi did you try opening a support ticket?

**Comment by Karan-Gandhi** [comment]
# No I haven't yet opened a support ticket. I will try opening one! Thank you.

**Comment by danielleadams** [comment]
@Karan-Gandhi do you mind if I close this? Just from my testing - I don't think is related to the Node.js buildpack.

**Comment by Karan-Gandhi** [comment]
Ok thank you for your time
