### ISSUE TITLE
Builds with Node LTS Version 12.18.3 are failing

### ISSUE THREAD

**Issue by ohsnapitscolin** [heroku/heroku-buildpack-nodejs#814]
Node's LTS Version was updated to 12.18.3 yesterday, but our Heroku builds are continuously failing on:
```
       Resolving node version 12 via semver.io...
       Downloading and installing node 12.18.3...
       Unable to download node 12.18.3; does it exist?
-----> Build failed
```

it seems like https://nodejs.org/dist/v12.18.3/node-v12.18.3-linux-x64.tar.gz exists, but I get don't just any output when running:
```
curl http://s3pository.heroku.com/node/v12.18.3/node-v12.18.3-linux-x64.tar.gz
```

Node 12.18.2 seems to be working fine:
```
curl http://s3pository.heroku.com/node/v12.18.2/node-v12.18.2-linux-x64.tar.gz
```

**Comment by danielleadams** [comment]
Hi @ohsnapitscolin, what version of the buildpack are you using? From the buildpack log, it doesn't look like you're using the latest.

**Comment by ohsnapitscolin** [comment]
Hey @danielleadams, we're actually using EmberJS, and https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/emberjs.tgz (https://github.com/heroku/heroku-buildpack-emberjs) which seems to be built on top of `heroku-buildpack-nodejs`.

**Comment by ohsnapitscolin** [comment]
Hmmm, as quick follow up looking in more detail at our logs, it looks like we are fetching `v98`. Trying to figure if that's an issue on our end or with the hosted emberjs.tgz buildpack above.
```
-----> emberjs app detected
-----> Setting NPM_CONFIG_PRODUCTION to false to install ember-cli toolchain
-----> Fetching buildpack heroku/nodejs-v98
-----> Node.js detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
-----> Installing binaries
       engines.node (package.json):  12
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 12 via semver.io...
       Downloading and installing node 12.18.3...
       Unable to download node 12.18.3; does it exist?
-----> Build failed
```

**Comment by ohsnapitscolin** [comment]
After a little more investigation, I've filed https://github.com/heroku/heroku-buildpack-emberjs/issues/61, and am going to close this issue on the `heroku-buildpack-nodejs` side. Thanks for the help!
