### ISSUE TITLE
How to use Yarn 2 with Zero-Install disabled?

### ISSUE THREAD

**Issue by JingBh** [heroku/heroku-buildpack-nodejs#823]
My project is using Yarn 2, and I didn't commit the packages cache in `.yarn/cache` directory because it will make my Git repository too big.

Now I want to deploy my app on Heroku, but the build process will automatically skip dependencies installation, which is causing failure.

<details>
<summary>This is my build log: (click to show)</summary>

```
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=false
       USE_YARN_CACHE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
 !     
      WARNING- You are using Yarn 2. The buildpack won't cache because Heroku is expecting dependencies from the .yarn directory for each build. To unset this and other similar environment variables, read here: https://devcenter.heroku.com/articles/migrating-to-yarn-2#change-environment-variables
      
       https://devcenter.heroku.com/articles/nodejs-support
       
-----> Installing binaries
       engines.node (package.json):  12.x
       engines.npm (package.json):   unspecified (use default)
       engines.yarn (package.json):  unspecified (use default)
       
       Resolving node version 12.x...
       Downloading and installing node 12.18.3
       Using default npm version: 6.14.6
       Resolving yarn version 1.x...
       Downloading and installing yarn (1.22.4)
       Using yarn 2.1.1
       
-----> Installing dependencies
       Heroku expects dependencies to be included in project with Yarn 2. Skipping installation.
       
-----> Build
       Running build (yarn)
       Usage Error: Couldn't find the node_modules state file - running an install might help (findPackageLocation)
       
       $ yarn run [--inspect] [--inspect-brk] <scriptName> ...
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

</details>

What should I do to make the build successful?

**Comment by danielleadams** [comment]
Hi @JingBh, thanks for opening this issue. We are working on making Yarn 2 better, and this will be available soon. We have an open pull request that will address this: https://github.com/heroku/heroku-buildpack-nodejs/pull/819, and we will need to make a few modifications after this in regards to caching to Heroku.

**Comment by danielleadams** [comment]
Fixed with https://github.com/heroku/heroku-buildpack-nodejs/pull/819. I'll release the buildpack tomorrow that will reflect these changes.

**Comment by dokmic** [comment]
Hey @danielleadams, I don't think that #819 resolves the issue.
You are using `yarn install --immutable --immutable-cache` to install the artifacts. The problem is that it will always fail when there is no cache, which is always the case when the Zero-Install is disabled.

I think `--immutable --immutable-cache` should be removed from that command.

**Comment by danielleadams** [comment]
Hi @dokmic, you're right. I closed this one by mistake. Thanks for pointing this out.

**Comment by danielleadams** [comment]
@JingBh this should be fixed with https://github.com/heroku/heroku-buildpack-nodejs/pull/836. Can you confirm please?

**Comment by JingBh** [comment]
@danielleadams Thanks, now the buildpack is working perfectly! :)
