### ISSUE TITLE
[Help] Need help deploying

### ISSUE THREAD

**Issue by CatchMeIfYouCan4401** [heroku/heroku-buildpack-nodejs#831]
I am very knew to Front End and Heroku.  
I downloaded https://github.com/nrandecker/particle  
After spending a lot of time I understood that deploying it would require both ruby and nodejs buildpack.  
Can somebody please guide me with simple steps on how I can deploy it on Heroku?

**Comment by danielleadams** [comment]
@CatchMeIfYouCan4401 Can you open a support ticket or use the Dev Center Getting Started guide? (https://devcenter.heroku.com/articles/getting-started-with-nodejs)
