### ISSUE TITLE
Unable to build local docker, archive/master.zip missing

### ISSUE THREAD

**Issue by mmmmmrob** [heroku/heroku-buildpack-nodejs#847]
Hi,

For a while now I've been building a local docker image configured like a heroku dyno to host local development. The image starts with Heroku-18:

```
FROM heroku/heroku:18
```

Build steps included:

```
RUN wget -q -O /heroku-buildpack-nodejs-master.zip https://github.com/heroku/heroku-buildpack-nodejs/archive/master.zip
RUN unzip -q /heroku-buildpack-nodejs-master.zip -d /
RUN /heroku-buildpack-nodejs-master/bin/detect $APPLICATION && /heroku-buildpack-nodejs-master/bin/compile $APPLICATION/ /tmp
```

This downloaded the nodejs buildpack and configured the docker image as if it were a dyno.

I've just gone to rebuild from scratch on a new machine and found the buildpack at `https://github.com/heroku/heroku-buildpack-nodejs/archive/master.zip` now returns 404.

I've replaced the `wget` with a `git clone`

```
RUN git clone https://github.com/heroku/heroku-buildpack-nodejs.git /heroku-buildpack-nodejs
```

Is this safe to use in this way to "recreate" a dyno locally?

Thanks

**Comment by judofyr** [comment]
The branch was renamed from `master` to `main` so you'll have to use https://github.com/heroku/heroku-buildpack-nodejs/archive/main.zip instead.

**Comment by mmmmmrob** [comment]
@judofyr thank you. I hadn't spotted the branch change.
