### ISSUE TITLE
Question about monorepos in Yarn 2

### ISSUE THREAD

**Issue by JakeMalis** [heroku/heroku-buildpack-nodejs#908]
I just read[ this article](https://blog.heroku.com/building-a-monorepo-with-yarn-2) about building a monorepo using Yarn 2 for
Heroku and had a two questions:
1. Our app has two repositories currently, the website and the API.
The website is a React app and the API is an ExpressJS app. When I
create the monorepo, do I have two different apps in my pipeline each
running a different Yarn workspace?
2. For review apps, which workspace will Heroku use to make the review app?

**Comment by danielleadams** [comment]
Hi @JakeMalis sorry for the delay here. You can use your top level package.json to direct Heroku to whatever directory you'd like, and run those commands. You can also use the same code base on multiple apps. Additionally, review apps will use the top level package.json scripts and route to the workspaces the same way the production build would.
