### ISSUE TITLE
npm ci not installing devDependencies despite NPM_CONFIG_PRODUCTION=false

### ISSUE THREAD

**Issue by schinery** [heroku/heroku-buildpack-nodejs#909]
**Issue:**

Despite setting `NPM_CONFIG_PRODUCTION=false` it appears that `devDependencies` aren't being installed when the `npm ci` or `npm install` tasks are run. 

From the build log below it shows `added 664 packages` were installed, but if I run `npm ci --production="false" --unsafe-perm --userconfig .npmrc` locally (what should be the same command as the buildpack) I get `added 1437 packages`. 

This then causes problems as the modules needed to compile the NextJS app aren't available. I know one option is too whack everything into `dependencies` but would rather not do that when the `devDependencies` should, at least according to the dcos, be available.

**Build Log:** 

```
-----> Building on the Heroku-20 stack
-----> Using buildpack: https://github.com/boxt/heroku-buildpack-nodejs
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_PRODUCTION=false
       NPM_CONFIG_LOGLEVEL=error
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       
-----> Installing binaries
       engines.node (package.json):  14.16.0
       engines.npm (package.json):   >=6.14.11
       
       Resolving node version 14.16.0...
       Downloading and installing node 14.16.0...
       Bootstrapping npm >=6.14.11 (replacing 6.14.11)...
       npm >=6.14.11 installed
       
-----> Restoring cache
       Invalidating cache due to a change in version of node, npm, yarn or stack
       Will not restore the following directories for this build:
         .next/cache
       
-----> Installing dependencies
       Installing node modules using --production="false"
       
       added 664 packages, and audited 665 packages in 39s
       
       found 0 vulnerabilities
       
-----> Build
       Running build
       
       > boxt-frontend@0.8.124 build
       > next build
       
       warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://err.sh/next.js/no-cache
       info  - Creating an optimized production build...
       Attention: Next.js now collects completely anonymous telemetry regarding usage.
       This information is used to shape Next.js' roadmap and prioritize features.
       You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
       https://nextjs.org/telemetry
       
It looks like you're trying to use TypeScript but do not have the required package(s) installed.
Please install typescript by running:
	npm install --save-dev typescript
If you are not trying to use TypeScript, please remove the tsconfig.json file from your package root (and any TypeScript files in your pages directory).
npm ERR! code 1
npm ERR! path /tmp/build_316ef31f
npm ERR! command failed
npm ERR! command sh -c next build
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.ZtPst/_logs/2021-03-24T17_29_49_030Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

**Versions:**

 - Heroku Stack: `heroku-20`
 - Node Version: `14.16.0`
 - NPM or Yarn Version: `NPM 6.14.11`
 - Buildpack Version: `heroku/nodejs v183` (latest)

**Additional context**

My initial thought was that `npm ci --production="$production"` was being called as `npm ci --production="true"` despite the config being set, but I tried [cloning this buildpack](https://github.com/boxt/heroku-buildpack-nodejs/commit/9a4c1b7a3e5373e0188ae58ccad749e55d4d5a6c) and added `echo "Installing node modules using --production=\"$production\""` to the output but this produced `Installing node modules using --production="false"` so it appears that is getting set correctly.

So is there something else in my config that could be causing the `devDependencies` to not be installed?

**Comment by schinery** [comment]
Ignore this, it does work as expected. 

However it is worth noting that I had to change the `engines` setting `"npm": ">=6.14.11"` to `"npm": "6.14.11"`. Not sure what the...  but this resolved things.

**Comment by bydga** [comment]
2 days ago, npm@7.7.0 was published and contained exactly this [bug](https://github.com/npm/cli/issues/2936): not installing devdeps regardless the --production flag. And 7.7.0 satisfies your engines.npm >=6.14.11... Anyways, npm@7.7.4 is already out - fixing this issue 🙂
