### ISSUE TITLE
Yarn 2: cache is deleted before pruning dev dependencies, making build slow

### ISSUE THREAD

**Issue by osdiab** [heroku/heroku-buildpack-nodejs#918]
**Describe the bug**
If you use yarn berry, the buildpack deletes the cache before pruning dev dependencies: https://github.com/heroku/heroku-buildpack-nodejs/blob/70af8362fb5d2c924a88beb0e837ee77804f67b6/lib/dependencies.sh#L183

The result is that my builds take way longer than they should because while the first cached build is super fast, when it prunes dev deps it ends up re-downloading all my deps. This sucks! I don't really understand the justification for deleting the cache there, but it adds around 2+ minutes to my builds for a task that should happen near instantly.

~~For now I'll just disable pruning with the `YARN_PRODUCTION=false` flag.~~ That doesn't work either, #906 

**Versions (please complete the following information):**
 - Heroku Stack: heroku-18
 - Node Version: 14
 - NPM or Yarn Version: yarn 2
 - Buildpack Version: latest from git

**Comment by danielleadams** [comment]
The cache is deleted because running the prune command does not actually remove the devDependencies. Right now, the cost of a smaller slug size is a longer build, but we can continue to investigate this to figure out if there's a better way to do this.

**Comment by osdiab** [comment]
Discussion on the yarn berry package suggests that yarn maintainers went the route of not building in this functionality but allowing people to offer it as a yarn plugin:

- https://github.com/yarnpkg/berry/issues/1789#issuecomment-705092566
- https://yarnpkg.com/features/plugins#contrib-plugins

**Comment by imajes** [comment]
@danielleadams, @heroku: is there a fix for this, or any movement? our build times have significantly decreased because of it, and i'm concious that it's just putting more pressure on yarn mirrors which are often provided out of generosity- downloading again because you've purged a cache is not very economical.

**Comment by danielleadams** [comment]
@imajes unfortunately, I left Heroku, so I'm no longer on this Issue.

**Comment by MaxMartiFoundry** [comment]
You can work around this by uninstalling the workspace-tools plugin before this step.

https://github.com/heroku/heroku-buildpack-nodejs/blob/5b3fac93c1d08c025620112b6cb479ee46a0db1f/lib/dependencies.sh#L177-L189

Add in package.json scripts:

```json
    "heroku-postbuild": "yarn plugin remove @yarnpkg/plugin-workspace-tools",
```

**Comment by lizthegrey** [comment]
@joshwlewis I think this is the thing you mentioned that is still remaining to fix wrt Yarn 2 parity

**Comment by lizthegrey** [comment]
Thanks for fixing this, v193 appears indeed to work. Hopefully a future v195 will contain the revert of the revert in v194!

**Comment by colincasey** [comment]
@lizthegrey v195 release does contain #999.  It's currently running for only 20% of builds but we'll roll it out more broadly if it appears to handle pruning without tripping over the edge case that caused us to revert #990.

**Comment by hibachrach** [comment]
I'm confused--this is still a problem, no? Can this issue be reopened? See #1056 as an example
