### ISSUE TITLE
Using with Yarn 3 stopped working on September 10

### ISSUE THREAD

**Issue by anark** [heroku/heroku-buildpack-nodejs#943]
**Describe the bug**
When deploying my application using yarn 3.0.0 after yarn runs I am seeing the following error
```
remote:        ➤ YN0013: │ react-hook-form@npm:7.15.3 can't be found in the cache and will be fetched from the remote registry
remote:        ➤ YN0056: │ react-hook-form@npm:7.15.3: Cache entry required but missing for react-hook-form@npm:7.15.3
remote:        ➤ YN0000: └ Completed in 1s 612ms
remote:        ➤ YN0000: Failed with errors in 2s 751ms
remote:
remote: -----> Build failed
remote:
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:
remote:        If you're stuck, please submit a ticket so we can help:
remote:        https://help.heroku.com/
remote:
remote:        Love,
remote:        Heroku
remote:
remote:  !     Push rejected, failed to compile Node.js app.
remote:
remote:  !     Push failed
```

Prior to September 10 this worked fine and would install any dependencies that were missing from the cache(new deps ect)

If I run `heroku builds:cache:purge`  to clear the build cache and then try the deploy it works fine.  However it is very slow to have to clear the build cache to make a deploy and it makes the deploy very slow.

**Versions (please complete the following information):**
 - Heroku Stack: `heroku-20`
 - Node Version: 14.x
 - NPM or Yarn Version: `Yarn 1.22.x`, `3.0.2`
 - Buildpack Version: `heroku/nodejs v188` seems to have worked in the previous buildpack

**Comment by anark** [comment]
I can confirm that when I switch buildpacks from `heroku/nodejs` to `https://github.com/heroku/heroku-buildpack-nodejs#v187`(v187) the builds work as expected and when switching back to `heroku/nodejs` I get this error again and have to purge the cache in order to release.

I believe the error may have something to do with the following error message
```
fsevents@patch:fsevents@npm%3A2.3.2#~builtin<compat/fsevents>::version=2.3.2&hash=1cc4b2 The platform linux is incompatible with this module, link skipped.
```

However when using version `v187` I could still deploy and use the cache, after the upgrade to `v188` I cannot.

**Comment by rachel-church** [comment]
@anark the `The platform linux is incompatible with this module` message is a red herring. After clearing the build cache the message is still there but the `yarn install` step succeeds for me. 

```
remote:        ➤ YN0000: ┌ Link step
remote:        ➤ YN0062: │ fsevents@patch:fsevents@npm%3A2.3.2#~builtin<compat/fsevents>::version=2.3.2&hash=1cc4b2 The platform linux is incompatible with this module, link skipped.
remote:        ➤ YN0062: │ fsevents@patch:fsevents@npm%3A1.2.13#~builtin<compat/fsevents>::version=1.2.13&hash=1cc4b2 The platform linux is incompatible with this module, link skipped.
remote:        ➤ YN0000: └ Completed in 39s 32ms
remote:        ➤ YN0000: Done with warnings in 2m 26s
```

There must be a bug in how the buildpack is handling the yarn cache or installed node modules.

My versions from the build logs:
```
       engines.node (package.json):  ^14.15.0
       engines.npm (package.json):   ^6.14.12
       engines.yarn (package.json):  unspecified (use default)
       
       Resolving node version ^14.15.0...
       Downloading and installing node 14.17.6...
       Bootstrapping npm ^6.14.12 (replacing 6.14.15)...
       npm ^6.14.12 installed
       Resolving yarn version 1.22.x...
       Downloading and installing yarn (1.22.11)
       Using yarn 3.0.1
```

**Comment by dirkkelly** [comment]
Can confirm this issue also with Yarn 2

I was able to resolve temporarily by disabling the build cache

`heroku config:set NODE_MODULES_CACHE=false`

We've also observed this doesn't impact initial builds, only subsequent ones. 

[Likely this is related change](https://github.com/heroku/heroku-buildpack-nodejs/compare/v187...v188#diff-a64a7d9b82578ca3053416d56631a61e0ceabed87619415663030e3842429e05R161)

**Comment by joshwlewis** [comment]
@anark, @rachel-church, @dirkkelly - Thanks for the reports and investigations. I have rolled back #888 in #944. I suspect this should resolve the issues you are seeing. Mind confirming that?

**Comment by anark** [comment]
Thanks @joshwlewis, I can confirm that I was able to deploy using `heroku/nodejs` buildpack without having to purge the cache.

That seems to have fixed my issue
