### ISSUE TITLE
Node process is suddenly killed during build ?

### ISSUE THREAD

**Issue by girardinsamuel** [heroku/heroku-buildpack-nodejs#958]
**Describe the bug**
Hi there ✋ !
I don't think that the bug is related to this buildpack but I really don't know where to look for help here...
I am building a web app and I have frontend code that I compile with Laravel Mix.

**To Reproduce**
I don't have something anyone can reproduce yet..

**Versions (please complete the following information):**
 - Node Version: [e.g. `14.8.1`]
 - NPM Version: [e.g. `7.24.2`]
 - Buildpack Version: [e.g. `latest`] 

**Additional context**
Start of the log
```
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-nodejs.git
=====> Detected Framework: Node.js

-----> Creating runtime environment

       NPM_CONFIG_LOGLEVEL=verbose
       USE_NPM_INSTALL=true
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=true

-----> Installing binaries
       engines.node (package.json):  14.x
       engines.npm (package.json):   7.x

       Resolving node version 14.x...
       Downloading and installing node 14.18.1...
       Bootstrapping npm 7.x (replacing 6.14.15)...
       npm 7.x installed
```

Suddenly sometimes during dependencies install or during compiling I got this error :

End of the log
```
 npm timing reifyNode:node_modules/simple-swizzle Completed in 100215ms
       /tmp/buildpackNH7OS/lib/monitor.sh: line 3:  1070 Killed                  "${@:-}"

-----> Build failed

       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys

       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
```

Does it mean that the buildpack killed node process because of something happened ? a timeout ? an exception ?

I define my env to be as verbose as possible.
Locally I can't reproduce when setting NODE_ENV to production.
Do you have by chance any guidelines that I can follow to track the problem ?

Thanks !

**Comment by joshwlewis** [comment]
Hi @girardinsamuel. The most likely causes for an error message like this are that the build went over the memory quota (2.5 GB) OR the build timed out (builds are limited to 15 minutes). 

My guess is that this was a memory overage. You might check to see if your build tooling (like eslint, react-scripts, webpack plugins etc.) have updates that might lower the usage.

**Comment by girardinsamuel** [comment]
Thanks for your answer !
I was using this buildpack with dokku and it was indeed a memory issue, I had to increase the swap space on the server where dokku was running.
More info here for reference: https://dokku.com/docs/getting-started/troubleshooting/#build-fails-with-killed-message
