### ISSUE TITLE
The unauthenticated git protocol on port 9418 is no longer supported

### ISSUE THREAD

**Issue by JoeyLi-1** [heroku/heroku-buildpack-nodejs#959]
**Describe the bug**
Installing dependencies
       Installing node modules
       npm ERR! Error while executing:
       npm ERR! /usr/bin/git ls-remote -h -t git://github.com/weo-edu/as-array.git
       npm ERR! 
       npm ERR! fatal: remote error: 
       npm ERR!   The unauthenticated git protocol on port 9418 is no longer supported.
       npm ERR! Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
       npm ERR! 
       npm ERR! exited with error code: 128
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.y0bJd/_logs/2021-11-02T14_09_53_910Z-debug.log

Just because this in my package-lock.json:
 "version": "git://github.com/weo-edu/as-array.git#17a37ea02091a778c18c0e84465ddfc5dd321df7

**Additional context**
I can use workaround https://github.com/heroku/heroku-buildpack-nodejs/issues/911 
But If you guys could fix the issue that will be very helpful.

Thank you very much!

**Comment by joshwlewis** [comment]
Hi @JoeyLi-1. This was a change on GitHub's end. The only fix we could make on our side would be to modify your `package-lock.json` in place and replace `git://github.com` with `https://github.com`. I'm not eager to rewrite lockfiles, though. There's potential to corrupt the file and/or surprise developers (lockfiles are expected to be locked!). I'd encourage you to make the change yourself if you haven't already.

**Comment by JoeyLi-1** [comment]
@joshwlewis  Thanks for your reply! I did change that file myself. Seems that is a solution now rather than a workaround.

**Comment by AravindKrishnamoorthy** [comment]
Running the below configuration and then executing build worked for us

git config --global url."https://".insteadOf git://

**Comment by mohammadusman666** [comment]
> Running the below configuration and then executing build worked for us
> 
> git config --global url."https://".insteadOf git://

Has anyone tried with Google App Engine deployment?

**Comment by TheHelias** [comment]
> Running the below configuration and then executing build worked for us
> 
> git config --global url."https://".insteadOf git://

Where do I run this? I ran it locally and it made no difference

**Comment by AravindKrishnamoorthy** [comment]
> > Running the below configuration and then executing build worked for us
> > git config --global url."https://".insteadOf git://
> 
> Where do I run this? I ran it locally and it made no difference

In the command prompt of the box where you are facing the error under discussion

**Comment by jeremydw** [comment]
> > Running the below configuration and then executing build worked for us
> > git config --global url."https://".insteadOf git://
> 
> Has anyone tried with Google App Engine deployment?

Yes. If by "Google App Engine deployment" you mean in the Google Cloud Build environment, you can run the following in a build step prior to the build step that installs dependencies:

```
git config --global url."https://".insteadOf git://
```

This fixed the problem for me.

**Comment by gxj1134506645** [comment]
I try to use [git config --global url."https://".insteadOf git://], but this method do not work, Now I can not clone project of github by https
