### ISSUE TITLE
Yarn Berry: override behaviour for `yarn_2_install` 

### ISSUE THREAD

**Issue by getlarge** [heroku/heroku-buildpack-nodejs#962]
**Describe the bug**
We are currently migrating to Yarn Berry and the last step is updating our Heroku deployment.
With the buildpack as is, i cannot go further in the installation step because an error is thrown at
```
       ➤ YN0000: ┌ Fetch step
       ➤ YN0013: │ esbuild-linux-64@npm:0.13.8 can't be found in the cache and will be fetched from the remote registry
       ➤ YN0056: │ esbuild-linux-64@npm:0.13.8: Cache entry required but missing for esbuild-linux-64@npm:0.13.8
       ➤ YN0000: └ Completed in 1s 233ms
       ➤ YN0000: Failed with errors in 2s 38ms
```

**To Reproduce**
No idea how to reproduce but probably any project relying on dependencies scoped to a specific OS might be sensitive to that issue

**Versions (please complete the following information):**
 - Heroku Stack: `heroku-20`
 - Node Version:`16.13.0`
 - NPM or Yarn Version:`Yarn 3.1`
 - Buildpack Version: `heroku/nodejs v189`

**Additional context**
I suspect that
1. `.yarn/cache` in our repository only contains `esbuild-darwin-64` as i'm working on MacOS (Intel), so that could be the reason why `esbuild-linux-64 ...can't be found in the cache` 
2. In [dependencies.sh](https://github.com/heroku/heroku-buildpack-nodejs/blob/main/lib/dependencies.sh#L143), the function detects the presence of  `.yarn/cache` so the option `--immutable-cache` is used, which would throw the error.

One possible quick solution would be to allow overriding the cache check condition by changing
```sh
if ! has_yarn_cache "$build_dir"
```
to

```sh
# in yarn_2.sh
use_yarn_cache() {
  local use_cache="$1"
  [[ "$use_cache" == "true" ]]
}

#in dependencies.sh
if ! has_yarn_cache "$build_dir" || ! use_yarn_cache "$USE_YARN_CACHE"
```

So when we set `USE_YARN_CACHE=false` we could avoid that problem.

Thanks in advance for your feedback and proposing a workaround.

**Comment by wrburgess** [comment]
Removing the `heroku/nodejs` buildpack is what worked for me in this particular instance

**Comment by lizthegrey** [comment]
Should probably be fixed by #978 now

**Comment by getlarge** [comment]
I will try it out next week and close the issue if everything works fine.

**Comment by getlarge** [comment]
Thank you, the issue seems resolved.
