### ISSUE TITLE
Bundle size increases after each deploy?

### ISSUE THREAD

**Issue by SylvainBigonneau** [heroku/heroku-buildpack-nodejs#965]
**Describe the bug**
Not sure if this is a bug or a misunderstanding, but I noticed that everytime I run a deploy for my Nuxt app (even without any change, just forcing a new one), at the end of the build, the logs give me a larger size (of about 1M for every new deploy) than the previous deploy:

```
-----> Compressing...
       Done: 102M
-----> Launching...
       Released v96
```

```
-----> Compressing...
       Done: 103.1M
-----> Launching...
       Released v97
```

```
-----> Compressing...
       Done: 104.4M
-----> Launching...
       Released v98
```

```
-----> Compressing...
       Done: 105.7M
-----> Launching...
       Released v99
```

I don't know if I'm reading it wrong, but I assumed that if I redeploy the exact same code again and again, I should end up with pretty much the same size every time, with maybe a little variation, but I really do not expect it to constantly increase at each and every deploy, which I guess is not very sustainable?

**To Reproduce**
1. Load a node app on  a dyno
2. Run deploy
3. Keep track of the compressed file size
4. Run deploy again
5. Read new compressed file size

**Versions:**
 - Heroku Stack: `heroku-20`
 - Node Version: `^12`
 - NPM or Yarn Version: `npm ^6`
 - Buildpack Version: unknown, probably latest

**Comment by joshwlewis** [comment]
Hi @SylvainBigonneau - No, I would not expect to see the cache grow by 1M each deploy of the same code, unless you have unbound dependencies (no package-lock.json, npm-shrinkwrap.json, or yarn.lock) which might be updated on each deploy.

Are you caching any custom directories? Or perhaps writing files manually to node_modules?

**Comment by SylvainBigonneau** [comment]
> Hi @SylvainBigonneau - No, I would not expect to see the cache grow by 1M each deploy of the same code, **unless you have unbound dependencies (no package-lock.json, npm-shrinkwrap.json, or yarn.lock)** which might be updated on each deploy.

Well dang, it seems like that was the issue. Committed my `yarn.lock` file and the increase stopped. Thank you for your help and apologies for the newbie issue.
