### ISSUE TITLE
Use yarn even when npm is in the engines list.

### ISSUE THREAD

**Issue by bopfer** [heroku/heroku-buildpack-nodejs#967]
**Describe the bug**

I am switching a repository over to yarn. To help with the transition I want to add an engines entry for npm to show a message.

Example:
```json
	"engines": {
		"node": "16.13.1",
		"npm": "Please use yarn in this repository",
		"yarn": "1.22.17"
	},
```

However, it seems that anytime npm is in the engines list, the buildpack will try to run npm commands instead of yarn.

Output from the heroku build:

```
-----> Building on the Heroku-18 stack
-----> Using buildpack: heroku/nodejs
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       USE_YARN_CACHE=true
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  16.13.1
       engines.npm (package.json):   Please use yarn in this repository
       engines.yarn (package.json):  1.22.17
       
       Resolving node version 16.13.1...
       Downloading and installing node 16.13.1...
       Bootstrapping npm Please use yarn in this repository (replacing 8.1.2)...
       Unable to install npm Please use yarn in this repository; does it exist?
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

Is there any way around this?

**To Reproduce**
See above

**Versions (please complete the following information):**
 - Heroku Stack: `heroku-18`
 - Node Version: `16.13.1`
 - NPM or Yarn Version: `Yarn 1.22.17`
 - Buildpack Version: latest (We just have `heroku/nodejs` in there)

**Additional context**

**Comment by joshwlewis** [comment]
@bopfer the buildpack will detect `yarn` if there is a `yarn.lock` in the project root. If your builds aren't detecting `yarn` my guess is `yarn.lock` might be ignored in `git`. Maybe check your `.gitignore`?

**Comment by bopfer** [comment]
@joshwlewis `yarn.lock` is not ignored by git. If I simply remove `npm` from the engines, then everything works fine with yarn.

It's not a big deal though. It was just something to help with the transition and everyone is used to it by now.  Feel free to close this if you want.
