### ISSUE TITLE
Update the default version of Node.js

### ISSUE THREAD

**Issue by brandon-welsch** [heroku/heroku-buildpack-nodejs#972]
**Is your enhancement request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The default version of Node.js (14) in this buildpack is currently in LTS Maintenance.

Is it possible to update the default version to use Node.js 16 (Active LTS)?

**Additional context**
https://nodejs.org/en/about/releases/

**Comment by joshwlewis** [comment]
@brandon-welsch yes, I believe we should be moving to default to Node.js 16 very soon. Thanks for the reminder.
